"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
import pydantic
from ttd_data_python.errors import TtddataError
from ttd_data_python.models import (
    advertiserdataserverresponseline as models_advertiserdataserverresponseline,
)
from ttd_data_python.types import BaseModel, OptionalNullable, UNSET
from typing import List, Optional
from typing_extensions import Annotated


class AdvertiserDataServerResponseErrorData(BaseModel):
    failed_lines: Annotated[
        OptionalNullable[
            List[
                models_advertiserdataserverresponseline.AdvertiserDataServerResponseLine
            ]
        ],
        pydantic.Field(alias="failedLines"),
    ] = UNSET


@dataclass(unsafe_hash=True)
class AdvertiserDataServerResponseError(TtddataError):
    data: AdvertiserDataServerResponseErrorData = field(hash=False)

    def __init__(
        self,
        data: AdvertiserDataServerResponseErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
