"""BeforeRequestHook that ensures ttd_data_sdk is always present in DataOrigins.

Behaviour:
  - If the caller provided DataOrigins (e.g. [ttd_databricks_sdk]), ttd_data_sdk is appended.
  - If the caller omitted DataOrigins entirely, it defaults to [ttd_data_sdk].

This file is not generated by Speakeasy and will not be overwritten on regeneration.
"""

import json

import httpx

from .types import BeforeRequestContext, BeforeRequestHook

_OPERATIONS = frozenset(
    {"IngestAdvertiserData", "IngestThirdPartyData", "IngestOfflineConversionData"}
)
_TTD_DATA_ORIGIN = {"Type": "Integration", "Id": "ttd_data_sdk"}


class DataOriginsHook(BeforeRequestHook):
    def before_request(
        self, hook_ctx: BeforeRequestContext, request: httpx.Request
    ) -> httpx.Request:
        # Hook is registered globally — skip operations that don't use DataOrigins.
        if hook_ctx.operation_id not in _OPERATIONS:
            return request

        body = json.loads(request.content)

        # Append ttd_data_sdk if not already present; handles both the omitted
        # (no DataOrigins key) and the caller-provided (e.g. [ttd_databricks_sdk]) cases.
        data_origin_list: list = body.get("DataOrigins") or []
        if not any(origin.get("Id") == "ttd_data_sdk" for origin in data_origin_list):
            data_origin_list.append(_TTD_DATA_ORIGIN)
        body["DataOrigins"] = data_origin_list

        new_content = json.dumps(body).encode()
        new_headers = dict(request.headers)
        # Recalculate Content-Length — the body grew after appending the new origin.
        new_headers["content-length"] = str(len(new_content))
        return httpx.Request(
            method=request.method,
            url=request.url,
            headers=new_headers,
            content=new_content,
        )