"""AfterErrorHook that normalizes plain-text error responses to application/json.

Some error responses return a plain string body with a missing or incorrect
content-type header, despite the OpenAPI spec declaring application/json.
This hook patches those responses so the SDK can deserialize them properly.

Behaviour:
  - If the response has no body, it is returned unchanged.
  - If the response already has application/json content-type, it is returned unchanged.
  - If the response has a plain-text body, it is wrapped as {"message": <text>}.
  - If the response has a body that is already valid JSON, the content-type is set
    to application/json and the body is left as-is.

This file is not generated by Speakeasy and will not be overwritten on regeneration.
"""

import json
from typing import Optional, Tuple, Union

import httpx

from .types import AfterErrorContext, AfterErrorHook


class PlainTextErrorNormalizer(AfterErrorHook):
    def after_error(
        self,
        hook_ctx: AfterErrorContext,
        response: Optional[httpx.Response],
        error: Optional[Exception],
    ) -> Union[Tuple[Optional[httpx.Response], Optional[Exception]], Exception]:
        if response is None:
            return response, error

        try:
            raw_text = response.text
        except UnicodeDecodeError:
            return response, error  # non-text body, nothing to normalize

        if not raw_text:
            return response, error

        content_type = response.headers.get("content-type", "")
        if "application/json" in content_type:
            return response, error

        try:
            json.loads(raw_text)
            body_bytes = raw_text.encode("utf-8")  # already valid JSON, just patch the header
        except (json.JSONDecodeError, ValueError):
            body_bytes = json.dumps({"message": raw_text}).encode("utf-8")  # wrap plain text

        # Strip content-encoding so httpx does not try to decompress the new uncompressed body.
        # Strip content-length so it is recomputed from the new body.
        new_headers = {k: v for k, v in response.headers.items() if k.lower() not in ("content-encoding", "content-length")}
        new_headers["content-type"] = "application/json"
        new_headers["content-length"] = str(len(body_bytes))

        response = httpx.Response(
            status_code=response.status_code,
            headers=new_headers,
            content=body_bytes,
            request=response.request,
        )

        return response, error
