"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c4bbecf8701c

from .dataerror import DataError
from .uid2serviceerror import UID2ServiceError
from typing import Any, TYPE_CHECKING

from ttd_data.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .advertiserdataserverresponse_error import (
        AdvertiserDataServerResponseError,
        AdvertiserDataServerResponseErrorData,
    )
    from .advertiserdsrresponse_error import (
        AdvertiserDsrResponseError,
        AdvertiserDsrResponseErrorData,
    )
    from .apierror import APIError
    from .merchantdsrresponse_error import (
        MerchantDsrResponseError,
        MerchantDsrResponseErrorData,
    )
    from .no_response_error import NoResponseError
    from .offlineconversiondataserverresponse_error import (
        OfflineConversionDataServerResponseError,
        OfflineConversionDataServerResponseErrorData,
    )
    from .responsevalidationerror import ResponseValidationError
    from .thirdpartydataserverresponse_error import (
        ThirdPartyDataServerResponseError,
        ThirdPartyDataServerResponseErrorData,
    )
    from .thirdpartydsrresponse_error import (
        ThirdPartyDsrResponseError,
        ThirdPartyDsrResponseErrorData,
    )

__all__ = [
    "APIError",
    "AdvertiserDataServerResponseError",
    "AdvertiserDataServerResponseErrorData",
    "AdvertiserDsrResponseError",
    "AdvertiserDsrResponseErrorData",
    "DataError",
    "MerchantDsrResponseError",
    "MerchantDsrResponseErrorData",
    "NoResponseError",
    "OfflineConversionDataServerResponseError",
    "OfflineConversionDataServerResponseErrorData",
    "ResponseValidationError",
    "UID2ServiceError",
    "ThirdPartyDataServerResponseError",
    "ThirdPartyDataServerResponseErrorData",
    "ThirdPartyDsrResponseError",
    "ThirdPartyDsrResponseErrorData",
]

_dynamic_imports: dict[str, str] = {
    "AdvertiserDataServerResponseError": ".advertiserdataserverresponse_error",
    "AdvertiserDataServerResponseErrorData": ".advertiserdataserverresponse_error",
    "AdvertiserDsrResponseError": ".advertiserdsrresponse_error",
    "AdvertiserDsrResponseErrorData": ".advertiserdsrresponse_error",
    "APIError": ".apierror",
    "MerchantDsrResponseError": ".merchantdsrresponse_error",
    "MerchantDsrResponseErrorData": ".merchantdsrresponse_error",
    "NoResponseError": ".no_response_error",
    "OfflineConversionDataServerResponseError": ".offlineconversiondataserverresponse_error",
    "OfflineConversionDataServerResponseErrorData": ".offlineconversiondataserverresponse_error",
    "ResponseValidationError": ".responsevalidationerror",
    "ThirdPartyDataServerResponseError": ".thirdpartydataserverresponse_error",
    "ThirdPartyDataServerResponseErrorData": ".thirdpartydataserverresponse_error",
    "ThirdPartyDsrResponseError": ".thirdpartydsrresponse_error",
    "ThirdPartyDsrResponseErrorData": ".thirdpartydsrresponse_error",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
