"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .dataerror import DataError
from typing import TYPE_CHECKING

from ttd_data.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .advertiserdataserverresponse_error import (
        AdvertiserDataServerResponseError,
        AdvertiserDataServerResponseErrorData,
    )
    from .apierror import APIError
    from .no_response_error import NoResponseError
    from .responsevalidationerror import ResponseValidationError

__all__ = [
    "APIError",
    "AdvertiserDataServerResponseError",
    "AdvertiserDataServerResponseErrorData",
    "DataError",
    "NoResponseError",
    "ResponseValidationError",
]

_dynamic_imports: dict[str, str] = {
    "AdvertiserDataServerResponseError": ".advertiserdataserverresponse_error",
    "AdvertiserDataServerResponseErrorData": ".advertiserdataserverresponse_error",
    "APIError": ".apierror",
    "NoResponseError": ".no_response_error",
    "ResponseValidationError": ".responsevalidationerror",
}


def __getattr__(attr_name: str) -> object:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
