"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d93ef12300f1

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
import pydantic
from ttd_data.errors import DataError
from ttd_data.models import (
    httpmetadata as models_httpmetadata,
    ipaddressdataserverresponseline as models_ipaddressdataserverresponseline,
)
from ttd_data.types import BaseModel, OptionalNullable, UNSET
from typing import List, Optional
from typing_extensions import Annotated


class IPAddressDataServerResponseErrorData(BaseModel):
    http_meta: Annotated[
        Optional[models_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None
    data_owner_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataOwnerId")
    ] = UNSET
    failed_lines: Annotated[
        OptionalNullable[
            List[models_ipaddressdataserverresponseline.IPAddressDataServerResponseLine]
        ],
        pydantic.Field(alias="FailedLines"),
    ] = UNSET


@dataclass(unsafe_hash=True)
class IPAddressDataServerResponseError(DataError):
    data: IPAddressDataServerResponseErrorData = field(hash=False)

    def __init__(
        self,
        data: IPAddressDataServerResponseErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
