"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from dataclasses import dataclass, field
import httpx
import pydantic
from ttd_data.errors import DataError
from ttd_data.models import (
    httpmetadata as models_httpmetadata,
    offlineconversiondataserverresponseline as models_offlineconversiondataserverresponseline,
)
from ttd_data.types import BaseModel, OptionalNullable, UNSET
from typing import List, Optional
from typing_extensions import Annotated


class OfflineConversionDataServerResponseErrorData(BaseModel):
    http_meta: Annotated[
        Optional[models_httpmetadata.HTTPMetadata], pydantic.Field(exclude=True)
    ] = None
    failed_lines: Annotated[
        OptionalNullable[
            List[
                models_offlineconversiondataserverresponseline.OfflineConversionDataServerResponseLine
            ]
        ],
        pydantic.Field(alias="FailedLines"),
    ] = UNSET


@dataclass(unsafe_hash=True)
class OfflineConversionDataServerResponseError(DataError):
    data: OfflineConversionDataServerResponseErrorData = field(hash=False)

    def __init__(
        self,
        data: OfflineConversionDataServerResponseErrorData,
        raw_response: httpx.Response,
        body: Optional[str] = None,
    ):
        message = body or raw_response.text
        super().__init__(message, raw_response, body)
        object.__setattr__(self, "data", data)
