"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from typing import TYPE_CHECKING

from ttd_data.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .advertiserdata import AdvertiserData, AdvertiserDataTypedDict
    from .advertiserdataitem import AdvertiserDataItem, AdvertiserDataItemTypedDict
    from .advertiserdatarequest import (
        AdvertiserDataRequest,
        AdvertiserDataRequestTypedDict,
    )
    from .advertiserdataresponseerrorcode import AdvertiserDataResponseErrorCode
    from .advertiserdataserverresponse import (
        AdvertiserDataServerResponse,
        AdvertiserDataServerResponseTypedDict,
    )
    from .advertiserdataserverresponseline import (
        AdvertiserDataServerResponseLine,
        AdvertiserDataServerResponseLineTypedDict,
    )
    from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
    from .ingestadvertiserdataop import (
        IngestAdvertiserDataRequest,
        IngestAdvertiserDataRequestTypedDict,
        IngestAdvertiserDataResponse,
        IngestAdvertiserDataResponseTypedDict,
    )

__all__ = [
    "AdvertiserData",
    "AdvertiserDataItem",
    "AdvertiserDataItemTypedDict",
    "AdvertiserDataRequest",
    "AdvertiserDataRequestTypedDict",
    "AdvertiserDataResponseErrorCode",
    "AdvertiserDataServerResponse",
    "AdvertiserDataServerResponseLine",
    "AdvertiserDataServerResponseLineTypedDict",
    "AdvertiserDataServerResponseTypedDict",
    "AdvertiserDataTypedDict",
    "HTTPMetadata",
    "HTTPMetadataTypedDict",
    "IngestAdvertiserDataRequest",
    "IngestAdvertiserDataRequestTypedDict",
    "IngestAdvertiserDataResponse",
    "IngestAdvertiserDataResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AdvertiserData": ".advertiserdata",
    "AdvertiserDataTypedDict": ".advertiserdata",
    "AdvertiserDataItem": ".advertiserdataitem",
    "AdvertiserDataItemTypedDict": ".advertiserdataitem",
    "AdvertiserDataRequest": ".advertiserdatarequest",
    "AdvertiserDataRequestTypedDict": ".advertiserdatarequest",
    "AdvertiserDataResponseErrorCode": ".advertiserdataresponseerrorcode",
    "AdvertiserDataServerResponse": ".advertiserdataserverresponse",
    "AdvertiserDataServerResponseTypedDict": ".advertiserdataserverresponse",
    "AdvertiserDataServerResponseLine": ".advertiserdataserverresponseline",
    "AdvertiserDataServerResponseLineTypedDict": ".advertiserdataserverresponseline",
    "HTTPMetadata": ".httpmetadata",
    "HTTPMetadataTypedDict": ".httpmetadata",
    "IngestAdvertiserDataRequest": ".ingestadvertiserdataop",
    "IngestAdvertiserDataRequestTypedDict": ".ingestadvertiserdataop",
    "IngestAdvertiserDataResponse": ".ingestadvertiserdataop",
    "IngestAdvertiserDataResponseTypedDict": ".ingestadvertiserdataop",
}


def __getattr__(attr_name: str) -> object:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
