"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 9cb05e16fec0

from typing import Any, TYPE_CHECKING

from ttd_data.utils.dynamic_imports import lazy_getattr, lazy_dir

if TYPE_CHECKING:
    from .advertiserdata import AdvertiserData, AdvertiserDataTypedDict
    from .advertiserdatarequest import (
        AdvertiserDataRequest,
        AdvertiserDataRequestTypedDict,
    )
    from .advertiserdataresponseerrorcode import AdvertiserDataResponseErrorCode
    from .advertiserdataserverresponse import (
        AdvertiserDataServerResponse,
        AdvertiserDataServerResponseTypedDict,
    )
    from .advertiserdataserverresponseline import (
        AdvertiserDataServerResponseLine,
        AdvertiserDataServerResponseLineTypedDict,
    )
    from .advertiserdsrfailedline import (
        AdvertiserDsrFailedLine,
        AdvertiserDsrFailedLineTypedDict,
    )
    from .advertiserdsrrequest import (
        AdvertiserDsrRequest,
        AdvertiserDsrRequestTypedDict,
    )
    from .advertiserdsrresponse import (
        AdvertiserDsrResponse,
        AdvertiserDsrResponseTypedDict,
    )
    from .baseadvertiserdataitem import (
        BaseAdvertiserDataItem,
        BaseAdvertiserDataItemTypedDict,
    )
    from .baseofflineconversiondataitem import (
        BaseOfflineConversionDataItem,
        BaseOfflineConversionDataItemTypedDict,
    )
    from .basepartnerdsrdataitem import (
        BasePartnerDsrDataItem,
        BasePartnerDsrDataItemTypedDict,
    )
    from .basethirdpartydataitem import (
        BaseThirdPartyDataItem,
        BaseThirdPartyDataItemTypedDict,
    )
    from .dataorigin import DataOrigin, DataOriginTypedDict
    from .dataorigintype import DataOriginType
    from .datasubjectrequestadvertiserdataop import (
        DATA_SUBJECT_REQUEST_ADVERTISER_DATA_OP_SERVERS,
        DataSubjectRequestAdvertiserDataResponse,
        DataSubjectRequestAdvertiserDataResponseTypedDict,
    )
    from .datasubjectrequestmerchantdataop import (
        DATA_SUBJECT_REQUEST_MERCHANT_DATA_OP_SERVERS,
        DataSubjectRequestMerchantDataResponse,
        DataSubjectRequestMerchantDataResponseTypedDict,
    )
    from .datasubjectrequestthirdpartydataop import (
        DATA_SUBJECT_REQUEST_THIRD_PARTY_DATA_OP_SERVERS,
        DataSubjectRequestThirdPartyDataResponse,
        DataSubjectRequestThirdPartyDataResponseTypedDict,
    )
    from .dsrerrorcode import DsrErrorCode
    from .expandedipaddress import ExpandedIPAddress, ExpandedIPAddressTypedDict
    from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
    from .ingestadvertiserdataop import (
        INGEST_ADVERTISER_DATA_OP_SERVERS,
        IngestAdvertiserDataResponse,
        IngestAdvertiserDataResponseTypedDict,
    )
    from .ingestfirstpartyipaddressdataop import (
        INGEST_FIRST_PARTY_IP_ADDRESS_DATA_OP_SERVERS,
        IngestFirstPartyIPAddressDataResponse,
        IngestFirstPartyIPAddressDataResponseTypedDict,
    )
    from .ingestofflineconversiondataop import (
        INGEST_OFFLINE_CONVERSION_DATA_OP_SERVERS,
        IngestOfflineConversionDataResponse,
        IngestOfflineConversionDataResponseTypedDict,
    )
    from .ingestthirdpartydataop import (
        INGEST_THIRD_PARTY_DATA_OP_SERVERS,
        IngestThirdPartyDataResponse,
        IngestThirdPartyDataResponseTypedDict,
    )
    from .ingestthirdpartyipaddressdataop import (
        INGEST_THIRD_PARTY_IP_ADDRESS_DATA_OP_SERVERS,
        IngestThirdPartyIPAddressDataResponse,
        IngestThirdPartyIPAddressDataResponseTypedDict,
    )
    from .ipaddressdata import IPAddressData, IPAddressDataTypedDict
    from .ipaddressdataitem import IPAddressDataItem, IPAddressDataItemTypedDict
    from .ipaddressdatarequest import (
        IPAddressDataRequest,
        IPAddressDataRequestTypedDict,
    )
    from .ipaddressdataresponseerrorcode import IPAddressDataResponseErrorCode
    from .ipaddressdataserverresponse import (
        IPAddressDataServerResponse,
        IPAddressDataServerResponseTypedDict,
    )
    from .ipaddressdataserverresponseline import (
        IPAddressDataServerResponseLine,
        IPAddressDataServerResponseLineTypedDict,
    )
    from .merchantdsrfailedline import (
        MerchantDsrFailedLine,
        MerchantDsrFailedLineTypedDict,
    )
    from .merchantdsrrequest import MerchantDsrRequest, MerchantDsrRequestTypedDict
    from .merchantdsrresponse import MerchantDsrResponse, MerchantDsrResponseTypedDict
    from .offlineconversiondatarequest import (
        OfflineConversionDataRequest,
        OfflineConversionDataRequestTypedDict,
    )
    from .offlineconversiondataresponseerrorcode import (
        OfflineConversionDataResponseErrorCode,
    )
    from .offlineconversiondataserverresponse import (
        OfflineConversionDataServerResponse,
        OfflineConversionDataServerResponseTypedDict,
    )
    from .offlineconversiondataserverresponseline import (
        OfflineConversionDataServerResponseLine,
        OfflineConversionDataServerResponseLineTypedDict,
    )
    from .partnerdsrrequesttype import PartnerDsrRequestType
    from .realtimeconversioneventlineitem import (
        RealTimeConversionEventLineItem,
        RealTimeConversionEventLineItemTypedDict,
    )
    from .realtimeconversioneventsprivacysetting import (
        RealTimeConversionEventsPrivacySetting,
        RealTimeConversionEventsPrivacySettingTypedDict,
    )
    from .security import Security, SecurityTypedDict
    from .thirdpartydata import ThirdPartyData, ThirdPartyDataTypedDict
    from .thirdpartydatarequest import (
        ThirdPartyDataRequest,
        ThirdPartyDataRequestTypedDict,
    )
    from .thirdpartydataresponseerrorcode import ThirdPartyDataResponseErrorCode
    from .thirdpartydataserverresponse import (
        ThirdPartyDataServerResponse,
        ThirdPartyDataServerResponseTypedDict,
    )
    from .thirdpartydataserverresponseline import (
        ThirdPartyDataServerResponseLine,
        ThirdPartyDataServerResponseLineTypedDict,
    )
    from .thirdpartydsrfailedline import (
        ThirdPartyDsrFailedLine,
        ThirdPartyDsrFailedLineTypedDict,
    )
    from .thirdpartydsrrequest import (
        ThirdPartyDsrRequest,
        ThirdPartyDsrRequestTypedDict,
    )
    from .thirdpartydsrresponse import (
        ThirdPartyDsrResponse,
        ThirdPartyDsrResponseTypedDict,
    )

__all__ = [
    "AdvertiserData",
    "AdvertiserDataRequest",
    "AdvertiserDataRequestTypedDict",
    "AdvertiserDataResponseErrorCode",
    "AdvertiserDataServerResponse",
    "AdvertiserDataServerResponseLine",
    "AdvertiserDataServerResponseLineTypedDict",
    "AdvertiserDataServerResponseTypedDict",
    "AdvertiserDataTypedDict",
    "AdvertiserDsrFailedLine",
    "AdvertiserDsrFailedLineTypedDict",
    "AdvertiserDsrRequest",
    "AdvertiserDsrRequestTypedDict",
    "AdvertiserDsrResponse",
    "AdvertiserDsrResponseTypedDict",
    "BaseAdvertiserDataItem",
    "BaseAdvertiserDataItemTypedDict",
    "BaseOfflineConversionDataItem",
    "BaseOfflineConversionDataItemTypedDict",
    "BasePartnerDsrDataItem",
    "BasePartnerDsrDataItemTypedDict",
    "BaseThirdPartyDataItem",
    "BaseThirdPartyDataItemTypedDict",
    "DATA_SUBJECT_REQUEST_ADVERTISER_DATA_OP_SERVERS",
    "DATA_SUBJECT_REQUEST_MERCHANT_DATA_OP_SERVERS",
    "DATA_SUBJECT_REQUEST_THIRD_PARTY_DATA_OP_SERVERS",
    "DataOrigin",
    "DataOriginType",
    "DataOriginTypedDict",
    "DataSubjectRequestAdvertiserDataResponse",
    "DataSubjectRequestAdvertiserDataResponseTypedDict",
    "DataSubjectRequestMerchantDataResponse",
    "DataSubjectRequestMerchantDataResponseTypedDict",
    "DataSubjectRequestThirdPartyDataResponse",
    "DataSubjectRequestThirdPartyDataResponseTypedDict",
    "DsrErrorCode",
    "ExpandedIPAddress",
    "ExpandedIPAddressTypedDict",
    "HTTPMetadata",
    "HTTPMetadataTypedDict",
    "INGEST_ADVERTISER_DATA_OP_SERVERS",
    "INGEST_FIRST_PARTY_IP_ADDRESS_DATA_OP_SERVERS",
    "INGEST_OFFLINE_CONVERSION_DATA_OP_SERVERS",
    "INGEST_THIRD_PARTY_DATA_OP_SERVERS",
    "INGEST_THIRD_PARTY_IP_ADDRESS_DATA_OP_SERVERS",
    "IPAddressData",
    "IPAddressDataItem",
    "IPAddressDataItemTypedDict",
    "IPAddressDataRequest",
    "IPAddressDataRequestTypedDict",
    "IPAddressDataResponseErrorCode",
    "IPAddressDataServerResponse",
    "IPAddressDataServerResponseLine",
    "IPAddressDataServerResponseLineTypedDict",
    "IPAddressDataServerResponseTypedDict",
    "IPAddressDataTypedDict",
    "IngestAdvertiserDataResponse",
    "IngestAdvertiserDataResponseTypedDict",
    "IngestFirstPartyIPAddressDataResponse",
    "IngestFirstPartyIPAddressDataResponseTypedDict",
    "IngestOfflineConversionDataResponse",
    "IngestOfflineConversionDataResponseTypedDict",
    "IngestThirdPartyDataResponse",
    "IngestThirdPartyDataResponseTypedDict",
    "IngestThirdPartyIPAddressDataResponse",
    "IngestThirdPartyIPAddressDataResponseTypedDict",
    "MerchantDsrFailedLine",
    "MerchantDsrFailedLineTypedDict",
    "MerchantDsrRequest",
    "MerchantDsrRequestTypedDict",
    "MerchantDsrResponse",
    "MerchantDsrResponseTypedDict",
    "OfflineConversionDataRequest",
    "OfflineConversionDataRequestTypedDict",
    "OfflineConversionDataResponseErrorCode",
    "OfflineConversionDataServerResponse",
    "OfflineConversionDataServerResponseLine",
    "OfflineConversionDataServerResponseLineTypedDict",
    "OfflineConversionDataServerResponseTypedDict",
    "PartnerDsrRequestType",
    "RealTimeConversionEventLineItem",
    "RealTimeConversionEventLineItemTypedDict",
    "RealTimeConversionEventsPrivacySetting",
    "RealTimeConversionEventsPrivacySettingTypedDict",
    "Security",
    "SecurityTypedDict",
    "ThirdPartyData",
    "ThirdPartyDataRequest",
    "ThirdPartyDataRequestTypedDict",
    "ThirdPartyDataResponseErrorCode",
    "ThirdPartyDataServerResponse",
    "ThirdPartyDataServerResponseLine",
    "ThirdPartyDataServerResponseLineTypedDict",
    "ThirdPartyDataServerResponseTypedDict",
    "ThirdPartyDataTypedDict",
    "ThirdPartyDsrFailedLine",
    "ThirdPartyDsrFailedLineTypedDict",
    "ThirdPartyDsrRequest",
    "ThirdPartyDsrRequestTypedDict",
    "ThirdPartyDsrResponse",
    "ThirdPartyDsrResponseTypedDict",
]

_dynamic_imports: dict[str, str] = {
    "AdvertiserData": ".advertiserdata",
    "AdvertiserDataTypedDict": ".advertiserdata",
    "AdvertiserDataRequest": ".advertiserdatarequest",
    "AdvertiserDataRequestTypedDict": ".advertiserdatarequest",
    "AdvertiserDataResponseErrorCode": ".advertiserdataresponseerrorcode",
    "AdvertiserDataServerResponse": ".advertiserdataserverresponse",
    "AdvertiserDataServerResponseTypedDict": ".advertiserdataserverresponse",
    "AdvertiserDataServerResponseLine": ".advertiserdataserverresponseline",
    "AdvertiserDataServerResponseLineTypedDict": ".advertiserdataserverresponseline",
    "AdvertiserDsrFailedLine": ".advertiserdsrfailedline",
    "AdvertiserDsrFailedLineTypedDict": ".advertiserdsrfailedline",
    "AdvertiserDsrRequest": ".advertiserdsrrequest",
    "AdvertiserDsrRequestTypedDict": ".advertiserdsrrequest",
    "AdvertiserDsrResponse": ".advertiserdsrresponse",
    "AdvertiserDsrResponseTypedDict": ".advertiserdsrresponse",
    "BaseAdvertiserDataItem": ".baseadvertiserdataitem",
    "BaseAdvertiserDataItemTypedDict": ".baseadvertiserdataitem",
    "BaseOfflineConversionDataItem": ".baseofflineconversiondataitem",
    "BaseOfflineConversionDataItemTypedDict": ".baseofflineconversiondataitem",
    "BasePartnerDsrDataItem": ".basepartnerdsrdataitem",
    "BasePartnerDsrDataItemTypedDict": ".basepartnerdsrdataitem",
    "BaseThirdPartyDataItem": ".basethirdpartydataitem",
    "BaseThirdPartyDataItemTypedDict": ".basethirdpartydataitem",
    "DataOrigin": ".dataorigin",
    "DataOriginTypedDict": ".dataorigin",
    "DataOriginType": ".dataorigintype",
    "DATA_SUBJECT_REQUEST_ADVERTISER_DATA_OP_SERVERS": ".datasubjectrequestadvertiserdataop",
    "DataSubjectRequestAdvertiserDataResponse": ".datasubjectrequestadvertiserdataop",
    "DataSubjectRequestAdvertiserDataResponseTypedDict": ".datasubjectrequestadvertiserdataop",
    "DATA_SUBJECT_REQUEST_MERCHANT_DATA_OP_SERVERS": ".datasubjectrequestmerchantdataop",
    "DataSubjectRequestMerchantDataResponse": ".datasubjectrequestmerchantdataop",
    "DataSubjectRequestMerchantDataResponseTypedDict": ".datasubjectrequestmerchantdataop",
    "DATA_SUBJECT_REQUEST_THIRD_PARTY_DATA_OP_SERVERS": ".datasubjectrequestthirdpartydataop",
    "DataSubjectRequestThirdPartyDataResponse": ".datasubjectrequestthirdpartydataop",
    "DataSubjectRequestThirdPartyDataResponseTypedDict": ".datasubjectrequestthirdpartydataop",
    "DsrErrorCode": ".dsrerrorcode",
    "ExpandedIPAddress": ".expandedipaddress",
    "ExpandedIPAddressTypedDict": ".expandedipaddress",
    "HTTPMetadata": ".httpmetadata",
    "HTTPMetadataTypedDict": ".httpmetadata",
    "INGEST_ADVERTISER_DATA_OP_SERVERS": ".ingestadvertiserdataop",
    "IngestAdvertiserDataResponse": ".ingestadvertiserdataop",
    "IngestAdvertiserDataResponseTypedDict": ".ingestadvertiserdataop",
    "INGEST_FIRST_PARTY_IP_ADDRESS_DATA_OP_SERVERS": ".ingestfirstpartyipaddressdataop",
    "IngestFirstPartyIPAddressDataResponse": ".ingestfirstpartyipaddressdataop",
    "IngestFirstPartyIPAddressDataResponseTypedDict": ".ingestfirstpartyipaddressdataop",
    "INGEST_OFFLINE_CONVERSION_DATA_OP_SERVERS": ".ingestofflineconversiondataop",
    "IngestOfflineConversionDataResponse": ".ingestofflineconversiondataop",
    "IngestOfflineConversionDataResponseTypedDict": ".ingestofflineconversiondataop",
    "INGEST_THIRD_PARTY_DATA_OP_SERVERS": ".ingestthirdpartydataop",
    "IngestThirdPartyDataResponse": ".ingestthirdpartydataop",
    "IngestThirdPartyDataResponseTypedDict": ".ingestthirdpartydataop",
    "INGEST_THIRD_PARTY_IP_ADDRESS_DATA_OP_SERVERS": ".ingestthirdpartyipaddressdataop",
    "IngestThirdPartyIPAddressDataResponse": ".ingestthirdpartyipaddressdataop",
    "IngestThirdPartyIPAddressDataResponseTypedDict": ".ingestthirdpartyipaddressdataop",
    "IPAddressData": ".ipaddressdata",
    "IPAddressDataTypedDict": ".ipaddressdata",
    "IPAddressDataItem": ".ipaddressdataitem",
    "IPAddressDataItemTypedDict": ".ipaddressdataitem",
    "IPAddressDataRequest": ".ipaddressdatarequest",
    "IPAddressDataRequestTypedDict": ".ipaddressdatarequest",
    "IPAddressDataResponseErrorCode": ".ipaddressdataresponseerrorcode",
    "IPAddressDataServerResponse": ".ipaddressdataserverresponse",
    "IPAddressDataServerResponseTypedDict": ".ipaddressdataserverresponse",
    "IPAddressDataServerResponseLine": ".ipaddressdataserverresponseline",
    "IPAddressDataServerResponseLineTypedDict": ".ipaddressdataserverresponseline",
    "MerchantDsrFailedLine": ".merchantdsrfailedline",
    "MerchantDsrFailedLineTypedDict": ".merchantdsrfailedline",
    "MerchantDsrRequest": ".merchantdsrrequest",
    "MerchantDsrRequestTypedDict": ".merchantdsrrequest",
    "MerchantDsrResponse": ".merchantdsrresponse",
    "MerchantDsrResponseTypedDict": ".merchantdsrresponse",
    "OfflineConversionDataRequest": ".offlineconversiondatarequest",
    "OfflineConversionDataRequestTypedDict": ".offlineconversiondatarequest",
    "OfflineConversionDataResponseErrorCode": ".offlineconversiondataresponseerrorcode",
    "OfflineConversionDataServerResponse": ".offlineconversiondataserverresponse",
    "OfflineConversionDataServerResponseTypedDict": ".offlineconversiondataserverresponse",
    "OfflineConversionDataServerResponseLine": ".offlineconversiondataserverresponseline",
    "OfflineConversionDataServerResponseLineTypedDict": ".offlineconversiondataserverresponseline",
    "PartnerDsrRequestType": ".partnerdsrrequesttype",
    "RealTimeConversionEventLineItem": ".realtimeconversioneventlineitem",
    "RealTimeConversionEventLineItemTypedDict": ".realtimeconversioneventlineitem",
    "RealTimeConversionEventsPrivacySetting": ".realtimeconversioneventsprivacysetting",
    "RealTimeConversionEventsPrivacySettingTypedDict": ".realtimeconversioneventsprivacysetting",
    "Security": ".security",
    "SecurityTypedDict": ".security",
    "ThirdPartyData": ".thirdpartydata",
    "ThirdPartyDataTypedDict": ".thirdpartydata",
    "ThirdPartyDataRequest": ".thirdpartydatarequest",
    "ThirdPartyDataRequestTypedDict": ".thirdpartydatarequest",
    "ThirdPartyDataResponseErrorCode": ".thirdpartydataresponseerrorcode",
    "ThirdPartyDataServerResponse": ".thirdpartydataserverresponse",
    "ThirdPartyDataServerResponseTypedDict": ".thirdpartydataserverresponse",
    "ThirdPartyDataServerResponseLine": ".thirdpartydataserverresponseline",
    "ThirdPartyDataServerResponseLineTypedDict": ".thirdpartydataserverresponseline",
    "ThirdPartyDsrFailedLine": ".thirdpartydsrfailedline",
    "ThirdPartyDsrFailedLineTypedDict": ".thirdpartydsrfailedline",
    "ThirdPartyDsrRequest": ".thirdpartydsrrequest",
    "ThirdPartyDsrRequestTypedDict": ".thirdpartydsrrequest",
    "ThirdPartyDsrResponse": ".thirdpartydsrresponse",
    "ThirdPartyDsrResponseTypedDict": ".thirdpartydsrresponse",
}


def __getattr__(attr_name: str) -> Any:
    return lazy_getattr(
        attr_name, package=__package__, dynamic_imports=_dynamic_imports
    )


def __dir__():
    return lazy_dir(dynamic_imports=_dynamic_imports)
