"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 547e907d3b1a

from __future__ import annotations
from ._basepartnerdsrdataitem import (
    BasePartnerDsrDataItem,
    BasePartnerDsrDataItemTypedDict,
)
from .partnerdsrrequesttype import PartnerDsrRequestType
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AdvertiserDsrRequestTypedDict(TypedDict):
    advertiser_id: NotRequired[Nullable[str]]
    data_provider_id: NotRequired[Nullable[str]]
    items: NotRequired[Nullable[List[BasePartnerDsrDataItemTypedDict]]]
    data_load_trace_id: NotRequired[Nullable[str]]
    request_type: NotRequired[PartnerDsrRequestType]


class AdvertiserDsrRequest(BaseModel):
    advertiser_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="AdvertiserId")
    ] = UNSET

    data_provider_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataProviderId")
    ] = UNSET

    items: Annotated[
        OptionalNullable[List[BasePartnerDsrDataItem]], pydantic.Field(alias="Items")
    ] = UNSET

    data_load_trace_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataLoadTraceId")
    ] = UNSET

    request_type: Annotated[
        Optional[PartnerDsrRequestType], pydantic.Field(alias="RequestType")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "AdvertiserId",
                "DataProviderId",
                "Items",
                "DataLoadTraceId",
                "RequestType",
            ]
        )
        nullable_fields = set(
            ["AdvertiserId", "DataProviderId", "Items", "DataLoadTraceId"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AdvertiserDsrRequest.model_rebuild()
except NameError:
    pass
