"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .advertiserdataitem import AdvertiserDataItem, AdvertiserDataItemTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class AdvertiserDataRequestTypedDict(TypedDict):
    advertiser_id: str
    data_provider_id: NotRequired[Nullable[str]]
    items: NotRequired[Nullable[List[AdvertiserDataItemTypedDict]]]


class AdvertiserDataRequest(BaseModel):
    advertiser_id: Annotated[str, pydantic.Field(alias="AdvertiserId")]

    data_provider_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataProviderId")
    ] = UNSET

    items: Annotated[
        OptionalNullable[List[AdvertiserDataItem]], pydantic.Field(alias="Items")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["DataProviderId", "Items"])
        nullable_fields = set(["DataProviderId", "Items"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AdvertiserDataRequest.model_rebuild()
except NameError:
    pass
