"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: ffcc1a785853

from __future__ import annotations
from enum import Enum


class AdvertiserDataResponseErrorCode(str, Enum):
    UNKNOWN = "Unknown"
    BASE_BID_CPM_METADATA_TOO_LONG = "BaseBidCPMMetadataTooLong"
    MISSING_USER_ID = "MissingUserId"
    USER_NOT_MAPPED = "UserNotMapped"
    DEPRECATED_MISSING_COOKIE_MAPPING_PARTNER_ID = (
        "Deprecated_MissingCookieMappingPartnerId"
    )
    INVALID_BID_FACTOR = "InvalidBidFactor"
    DATA_NAME_TOO_LONG = "DataNameTooLong"
    INVALID_TTL_IN_MINUTES = "InvalidTtlInMinutes"
    INVALID_BASE_BID_CPM = "InvalidBaseBidCPM"
    INVALID_DATA_OWNER_ID = "InvalidDataOwnerId"
    INVALID_PARAMETER_FORMAT = "InvalidParameterFormat"
    TARGETING_DATA_CREATION_LIMIT_EXCEEDED = "TargetingDataCreationLimitExceeded"
    TARGETING_DATA_COUNT_LIMIT_EXCEEDED = "TargetingDataCountLimitExceeded"
    TENANT_RESTRICTIONS_EXTERNAL_DATA = "TenantRestrictionsExternalData"
    TARGETING_DATA_DISABLED = "TargetingDataDisabled"
    ITEM_DESERIALIZATION_ERROR = "ItemDeserializationError"
    UID2_ERROR = "Uid2Error"
