"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing_extensions import Annotated, NotRequired, TypedDict


class AdvertiserDataTypedDict(TypedDict):
    name: str
    base_bid_cpm: NotRequired[Nullable[float]]
    base_bid_cpm_metadata: NotRequired[Nullable[str]]
    bid_factor: NotRequired[Nullable[float]]
    timestamp_utc: NotRequired[Nullable[datetime]]
    ttl_in_minutes: NotRequired[Nullable[int]]


class AdvertiserData(BaseModel):
    name: str

    base_bid_cpm: Annotated[
        OptionalNullable[float], pydantic.Field(alias="baseBidCPM")
    ] = UNSET

    base_bid_cpm_metadata: Annotated[
        OptionalNullable[str], pydantic.Field(alias="baseBidCPMMetadata")
    ] = UNSET

    bid_factor: Annotated[
        OptionalNullable[float], pydantic.Field(alias="bidFactor")
    ] = UNSET

    timestamp_utc: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="timestampUtc")
    ] = UNSET

    ttl_in_minutes: Annotated[
        OptionalNullable[int], pydantic.Field(alias="ttlInMinutes")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "baseBidCPM",
                "baseBidCPMMetadata",
                "bidFactor",
                "timestampUtc",
                "ttlInMinutes",
            ]
        )
        nullable_fields = set(
            [
                "baseBidCPM",
                "baseBidCPMMetadata",
                "bidFactor",
                "timestampUtc",
                "ttlInMinutes",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
