"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dsrerrorcode import DsrErrorCode
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AdvertiserDsrFailedLineTypedDict(TypedDict):
    tdid: NotRequired[Nullable[str]]
    error_code: NotRequired[DsrErrorCode]
    message: NotRequired[Nullable[str]]
    advertiser_id: NotRequired[Nullable[str]]
    data_provider_id: NotRequired[Nullable[str]]


class AdvertiserDsrFailedLine(BaseModel):
    tdid: Annotated[OptionalNullable[str], pydantic.Field(alias="TDID")] = UNSET

    error_code: Annotated[Optional[DsrErrorCode], pydantic.Field(alias="ErrorCode")] = (
        None
    )

    message: Annotated[OptionalNullable[str], pydantic.Field(alias="Message")] = UNSET

    advertiser_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="AdvertiserId")
    ] = UNSET

    data_provider_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataProviderId")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["TDID", "ErrorCode", "Message", "AdvertiserId", "DataProviderId"]
        )
        nullable_fields = set(["TDID", "Message", "AdvertiserId", "DataProviderId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    AdvertiserDsrFailedLine.model_rebuild()
except NameError:
    pass
