"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .advertiserdataresponseerrorcode import AdvertiserDataResponseErrorCode
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class AdvertiserDataServerResponseLineTypedDict(TypedDict):
    tdid: NotRequired[Nullable[str]]
    data_name: NotRequired[Nullable[str]]
    error_code: NotRequired[AdvertiserDataResponseErrorCode]
    message: NotRequired[Nullable[str]]


class AdvertiserDataServerResponseLine(BaseModel):
    tdid: OptionalNullable[str] = UNSET

    data_name: Annotated[OptionalNullable[str], pydantic.Field(alias="dataName")] = (
        UNSET
    )

    error_code: Annotated[
        Optional[AdvertiserDataResponseErrorCode], pydantic.Field(alias="errorCode")
    ] = None

    message: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tdid", "dataName", "errorCode", "message"])
        nullable_fields = set(["tdid", "dataName", "message"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
