"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class AdvertiserDataResponseErrorCode(str, Enum):
    UNKNOWN = "Unknown"
    BASE_BID_CPM_METADATA_TOO_LONG = "BaseBidCPMMetadataTooLong"
    MISSING_USER_ID = "MissingUserId"
    USER_NOT_MAPPED = "UserNotMapped"
    DEPRECATED_MISSING_COOKIE_MAPPING_PARTNER_ID = (
        "Deprecated_MissingCookieMappingPartnerId"
    )
    INVALID_BID_FACTOR = "InvalidBidFactor"
    DATA_NAME_TOO_LONG = "DataNameTooLong"
    INVALID_TTL_IN_MINUTES = "InvalidTtlInMinutes"
    INVALID_BASE_BID_CPM = "InvalidBaseBidCPM"
