"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7922701d5b7f

from __future__ import annotations
from .realtimeconversioneventlineitem import (
    RealTimeConversionEventLineItem,
    RealTimeConversionEventLineItemTypedDict,
)
from .realtimeconversioneventsprivacysetting import (
    RealTimeConversionEventsPrivacySetting,
    RealTimeConversionEventsPrivacySettingTypedDict,
)
from datetime import datetime
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class BaseOfflineConversionDataItemTypedDict(TypedDict):
    tracking_tag_id: str
    timestamp_utc: datetime
    tdid: NotRequired[Nullable[str]]
    daid: NotRequired[Nullable[str]]
    uid2: NotRequired[Nullable[str]]
    uid2_token: NotRequired[Nullable[str]]
    ramp_id: NotRequired[Nullable[str]]
    euid: NotRequired[Nullable[str]]
    euid_token: NotRequired[Nullable[str]]
    data_provider_user_id: NotRequired[Nullable[str]]
    user_id_array: NotRequired[Nullable[List[List[str]]]]
    r"""Array of [type, id] pairs."""
    cookie_mapping_partner_id: NotRequired[Nullable[str]]
    order_id: NotRequired[Nullable[str]]
    impression_id: NotRequired[Nullable[str]]
    value: NotRequired[Nullable[str]]
    value_currency: NotRequired[Nullable[str]]
    country: NotRequired[Nullable[str]]
    region: NotRequired[Nullable[str]]
    metro: NotRequired[Nullable[str]]
    city: NotRequired[Nullable[str]]
    merchant_id: NotRequired[Nullable[str]]
    event_name: NotRequired[Nullable[str]]
    line_items: NotRequired[Nullable[List[RealTimeConversionEventLineItemTypedDict]]]
    privacy_settings: NotRequired[
        Nullable[List[RealTimeConversionEventsPrivacySettingTypedDict]]
    ]
    td1: NotRequired[Nullable[str]]
    td2: NotRequired[Nullable[str]]
    td3: NotRequired[Nullable[str]]
    td4: NotRequired[Nullable[str]]
    td5: NotRequired[Nullable[str]]
    td6: NotRequired[Nullable[str]]
    td7: NotRequired[Nullable[str]]
    td8: NotRequired[Nullable[str]]
    td9: NotRequired[Nullable[str]]
    td10: NotRequired[Nullable[str]]


class BaseOfflineConversionDataItem(BaseModel):
    tracking_tag_id: Annotated[str, pydantic.Field(alias="TrackingTagId")]

    timestamp_utc: Annotated[datetime, pydantic.Field(alias="TimestampUtc")]

    tdid: Annotated[OptionalNullable[str], pydantic.Field(alias="TDID")] = UNSET

    daid: Annotated[OptionalNullable[str], pydantic.Field(alias="DAID")] = UNSET

    uid2: Annotated[OptionalNullable[str], pydantic.Field(alias="UID2")] = UNSET

    uid2_token: Annotated[OptionalNullable[str], pydantic.Field(alias="UID2Token")] = (
        UNSET
    )

    ramp_id: Annotated[OptionalNullable[str], pydantic.Field(alias="RampID")] = UNSET

    euid: Annotated[OptionalNullable[str], pydantic.Field(alias="EUID")] = UNSET

    euid_token: Annotated[OptionalNullable[str], pydantic.Field(alias="EUIDToken")] = (
        UNSET
    )

    data_provider_user_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataProviderUserId")
    ] = UNSET

    user_id_array: Annotated[
        OptionalNullable[List[List[str]]], pydantic.Field(alias="UserIdArray")
    ] = UNSET
    r"""Array of [type, id] pairs."""

    cookie_mapping_partner_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="CookieMappingPartnerId")
    ] = UNSET

    order_id: Annotated[OptionalNullable[str], pydantic.Field(alias="OrderId")] = UNSET

    impression_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="ImpressionId")
    ] = UNSET

    value: Annotated[OptionalNullable[str], pydantic.Field(alias="Value")] = UNSET

    value_currency: Annotated[
        OptionalNullable[str], pydantic.Field(alias="ValueCurrency")
    ] = UNSET

    country: Annotated[OptionalNullable[str], pydantic.Field(alias="Country")] = UNSET

    region: Annotated[OptionalNullable[str], pydantic.Field(alias="Region")] = UNSET

    metro: Annotated[OptionalNullable[str], pydantic.Field(alias="Metro")] = UNSET

    city: Annotated[OptionalNullable[str], pydantic.Field(alias="City")] = UNSET

    merchant_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="MerchantId")
    ] = UNSET

    event_name: Annotated[OptionalNullable[str], pydantic.Field(alias="EventName")] = (
        UNSET
    )

    line_items: Annotated[
        OptionalNullable[List[RealTimeConversionEventLineItem]],
        pydantic.Field(alias="LineItems"),
    ] = UNSET

    privacy_settings: Annotated[
        OptionalNullable[List[RealTimeConversionEventsPrivacySetting]],
        pydantic.Field(alias="PrivacySettings"),
    ] = UNSET

    td1: Annotated[OptionalNullable[str], pydantic.Field(alias="TD1")] = UNSET

    td2: Annotated[OptionalNullable[str], pydantic.Field(alias="TD2")] = UNSET

    td3: Annotated[OptionalNullable[str], pydantic.Field(alias="TD3")] = UNSET

    td4: Annotated[OptionalNullable[str], pydantic.Field(alias="TD4")] = UNSET

    td5: Annotated[OptionalNullable[str], pydantic.Field(alias="TD5")] = UNSET

    td6: Annotated[OptionalNullable[str], pydantic.Field(alias="TD6")] = UNSET

    td7: Annotated[OptionalNullable[str], pydantic.Field(alias="TD7")] = UNSET

    td8: Annotated[OptionalNullable[str], pydantic.Field(alias="TD8")] = UNSET

    td9: Annotated[OptionalNullable[str], pydantic.Field(alias="TD9")] = UNSET

    td10: Annotated[OptionalNullable[str], pydantic.Field(alias="TD10")] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "TDID",
                "DAID",
                "UID2",
                "UID2Token",
                "RampID",
                "EUID",
                "EUIDToken",
                "DataProviderUserId",
                "UserIdArray",
                "CookieMappingPartnerId",
                "OrderId",
                "ImpressionId",
                "Value",
                "ValueCurrency",
                "Country",
                "Region",
                "Metro",
                "City",
                "MerchantId",
                "EventName",
                "LineItems",
                "PrivacySettings",
                "TD1",
                "TD2",
                "TD3",
                "TD4",
                "TD5",
                "TD6",
                "TD7",
                "TD8",
                "TD9",
                "TD10",
            ]
        )
        nullable_fields = set(
            [
                "TDID",
                "DAID",
                "UID2",
                "UID2Token",
                "RampID",
                "EUID",
                "EUIDToken",
                "DataProviderUserId",
                "UserIdArray",
                "CookieMappingPartnerId",
                "OrderId",
                "ImpressionId",
                "Value",
                "ValueCurrency",
                "Country",
                "Region",
                "Metro",
                "City",
                "MerchantId",
                "EventName",
                "LineItems",
                "PrivacySettings",
                "TD1",
                "TD2",
                "TD3",
                "TD4",
                "TD5",
                "TD6",
                "TD7",
                "TD8",
                "TD9",
                "TD10",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    BaseOfflineConversionDataItem.model_rebuild()
except NameError:
    pass
