"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: df8b7792ffe1

from __future__ import annotations
from .advertiserdata import AdvertiserData, AdvertiserDataTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class BaseAdvertiserDataItemTypedDict(TypedDict):
    data: List[AdvertiserDataTypedDict]
    tdid: NotRequired[Nullable[str]]
    daid: NotRequired[Nullable[str]]
    uid2: NotRequired[Nullable[str]]
    uid2_token: NotRequired[Nullable[str]]
    ramp_id: NotRequired[Nullable[str]]
    core_id: NotRequired[Nullable[str]]
    euid: NotRequired[Nullable[str]]
    euid_token: NotRequired[Nullable[str]]
    id5: NotRequired[Nullable[str]]
    net_id: NotRequired[Nullable[str]]
    first_id: NotRequired[Nullable[str]]
    utiq_id: NotRequired[Nullable[str]]
    merkury_id: NotRequired[Nullable[str]]
    iqvia_ppid: NotRequired[Nullable[str]]
    cookie_mapping_partner_id: NotRequired[Nullable[str]]


class BaseAdvertiserDataItem(BaseModel):
    data: Annotated[List[AdvertiserData], pydantic.Field(alias="Data")]

    tdid: Annotated[OptionalNullable[str], pydantic.Field(alias="TDID")] = UNSET

    daid: Annotated[OptionalNullable[str], pydantic.Field(alias="DAID")] = UNSET

    uid2: Annotated[OptionalNullable[str], pydantic.Field(alias="UID2")] = UNSET

    uid2_token: Annotated[OptionalNullable[str], pydantic.Field(alias="UID2Token")] = (
        UNSET
    )

    ramp_id: Annotated[OptionalNullable[str], pydantic.Field(alias="RampID")] = UNSET

    core_id: Annotated[OptionalNullable[str], pydantic.Field(alias="CoreID")] = UNSET

    euid: Annotated[OptionalNullable[str], pydantic.Field(alias="EUID")] = UNSET

    euid_token: Annotated[OptionalNullable[str], pydantic.Field(alias="EUIDToken")] = (
        UNSET
    )

    id5: Annotated[OptionalNullable[str], pydantic.Field(alias="ID5")] = UNSET

    net_id: Annotated[OptionalNullable[str], pydantic.Field(alias="NetID")] = UNSET

    first_id: Annotated[OptionalNullable[str], pydantic.Field(alias="FirstID")] = UNSET

    utiq_id: Annotated[OptionalNullable[str], pydantic.Field(alias="UtiqID")] = UNSET

    merkury_id: Annotated[OptionalNullable[str], pydantic.Field(alias="MerkuryID")] = (
        UNSET
    )

    iqvia_ppid: Annotated[OptionalNullable[str], pydantic.Field(alias="IqviaPPID")] = (
        UNSET
    )

    cookie_mapping_partner_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="CookieMappingPartnerId")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "TDID",
                "DAID",
                "UID2",
                "UID2Token",
                "RampID",
                "CoreID",
                "EUID",
                "EUIDToken",
                "ID5",
                "NetID",
                "FirstID",
                "UtiqID",
                "MerkuryID",
                "IqviaPPID",
                "CookieMappingPartnerId",
            ]
        )
        nullable_fields = set(
            [
                "TDID",
                "DAID",
                "UID2",
                "UID2Token",
                "RampID",
                "CoreID",
                "EUID",
                "EUIDToken",
                "ID5",
                "NetID",
                "FirstID",
                "UtiqID",
                "MerkuryID",
                "IqviaPPID",
                "CookieMappingPartnerId",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    BaseAdvertiserDataItem.model_rebuild()
except NameError:
    pass
