"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class DataOriginType(str, Enum):
    ADVERTISER = "Advertiser"
    DATA_PROVIDER = "DataProvider"
    INTEGRATION = "Integration"
    ONBOARDER = "Onboarder"
