"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .merchantdsrrequest import MerchantDsrRequest, MerchantDsrRequestTypedDict
from .merchantdsrresponse import MerchantDsrResponse, MerchantDsrResponseTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from ttd_data.utils import FieldMetadata, HeaderMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


DATA_SUBJECT_REQUEST_MERCHANT_DATA_OP_SERVERS = [
    "https://usw-data.adsrvr.org",
]


class DataSubjectRequestMerchantDataRequestTypedDict(TypedDict):
    ttd_auth: str
    r"""Data API token for authentication."""
    body: MerchantDsrRequestTypedDict


class DataSubjectRequestMerchantDataRequest(BaseModel):
    ttd_auth: Annotated[
        str,
        pydantic.Field(alias="TTD-Auth"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Data API token for authentication."""

    body: Annotated[
        MerchantDsrRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class DataSubjectRequestMerchantDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    merchant_dsr_response: NotRequired[MerchantDsrResponseTypedDict]
    r"""Success"""


class DataSubjectRequestMerchantDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    merchant_dsr_response: Optional[MerchantDsrResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["MerchantDsrResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
