"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .dataorigintype import DataOriginType
import pydantic
from ttd_data.types import BaseModel
from typing_extensions import Annotated, TypedDict


class DataOriginTypedDict(TypedDict):
    id: str
    type: DataOriginType


class DataOrigin(BaseModel):
    id: Annotated[str, pydantic.Field(alias="Id")]

    type: Annotated[DataOriginType, pydantic.Field(alias="Type")]


try:
    DataOrigin.model_rebuild()
except NameError:
    pass
