"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 961430b7540f

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .thirdpartydsrrequest import ThirdPartyDsrRequest, ThirdPartyDsrRequestTypedDict
from .thirdpartydsrresponse import ThirdPartyDsrResponse, ThirdPartyDsrResponseTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from ttd_data.utils import FieldMetadata, HeaderMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


DATA_SUBJECT_REQUEST_THIRD_PARTY_DATA_OP_SERVERS = [
    "https://usw-data.adsrvr.org",
]


class DataSubjectRequestThirdPartyDataRequestTypedDict(TypedDict):
    ttd_auth: str
    r"""Data API token for authentication."""
    body: ThirdPartyDsrRequestTypedDict


class DataSubjectRequestThirdPartyDataRequest(BaseModel):
    ttd_auth: Annotated[
        str,
        pydantic.Field(alias="TTD-Auth"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Data API token for authentication."""

    body: Annotated[
        ThirdPartyDsrRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class DataSubjectRequestThirdPartyDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    third_party_dsr_response: NotRequired[ThirdPartyDsrResponseTypedDict]
    r"""Success"""


class DataSubjectRequestThirdPartyDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    third_party_dsr_response: Optional[ThirdPartyDsrResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ThirdPartyDsrResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
