"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 32f041f202c4

from __future__ import annotations
from .advertiserdsrrequest import AdvertiserDsrRequest, AdvertiserDsrRequestTypedDict
from .advertiserdsrresponse import AdvertiserDsrResponse, AdvertiserDsrResponseTypedDict
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from ttd_data.utils import FieldMetadata, HeaderMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


DATA_SUBJECT_REQUEST_ADVERTISER_DATA_OP_SERVERS = [
    "https://usw-data.adsrvr.org",
]


class DataSubjectRequestAdvertiserDataRequestTypedDict(TypedDict):
    ttd_auth: str
    r"""Data API token for authentication."""
    body: AdvertiserDsrRequestTypedDict


class DataSubjectRequestAdvertiserDataRequest(BaseModel):
    ttd_auth: Annotated[
        str,
        pydantic.Field(alias="TTD-Auth"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Data API token for authentication."""

    body: Annotated[
        AdvertiserDsrRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class DataSubjectRequestAdvertiserDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    advertiser_dsr_response: NotRequired[AdvertiserDsrResponseTypedDict]
    r"""Success"""


class DataSubjectRequestAdvertiserDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    advertiser_dsr_response: Optional[AdvertiserDsrResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["AdvertiserDsrResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
