"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 2eaf568ecc7c

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .merchantdsrresponse import MerchantDsrResponse, MerchantDsrResponseTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


DATA_SUBJECT_REQUEST_MERCHANT_DATA_OP_SERVERS = [
    "https://usw-data.adsrvr.org",
]


class DataSubjectRequestMerchantDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    merchant_dsr_response: NotRequired[MerchantDsrResponseTypedDict]
    r"""Success"""


class DataSubjectRequestMerchantDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    merchant_dsr_response: Optional[MerchantDsrResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["MerchantDsrResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
