"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class DsrErrorCode(str, Enum):
    UNKNOWN = "Unknown"
    INVALID_USER_ID = "InvalidUserId"
