"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 3d91ba4e034b

from __future__ import annotations
from enum import Enum


class DsrErrorCode(str, Enum):
    UNKNOWN = "Unknown"
    INVALID_USER_ID = "InvalidUserId"
    UID2_ERROR = "Uid2Error"
