"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 128a16de40f5

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing_extensions import Annotated, NotRequired, TypedDict


class ExpandedIPAddressTypedDict(TypedDict):
    ip_address: NotRequired[Nullable[str]]
    ip_address_range: NotRequired[Nullable[str]]
    targeting_data_metadata_id: NotRequired[Nullable[int]]


class ExpandedIPAddress(BaseModel):
    ip_address: Annotated[OptionalNullable[str], pydantic.Field(alias="IPAddress")] = (
        UNSET
    )

    ip_address_range: Annotated[
        OptionalNullable[str], pydantic.Field(alias="IPAddressRange")
    ] = UNSET

    targeting_data_metadata_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="TargetingDataMetadataId")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["IPAddress", "IPAddressRange", "TargetingDataMetadataId"]
        )
        nullable_fields = set(
            ["IPAddress", "IPAddressRange", "TargetingDataMetadataId"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ExpandedIPAddress.model_rebuild()
except NameError:
    pass
