"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .offlineconversiondatarequest import (
    OfflineConversionDataRequest,
    OfflineConversionDataRequestTypedDict,
)
from .offlineconversiondataserverresponse import (
    OfflineConversionDataServerResponse,
    OfflineConversionDataServerResponseTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from ttd_data.utils import FieldMetadata, HeaderMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


INGEST_OFFLINE_CONVERSION_DATA_OP_SERVERS = [
    "https://offlineattrib.adsrvr.org",
]


class IngestOfflineConversionDataRequestTypedDict(TypedDict):
    ttd_auth: str
    r"""Data API token for authentication."""
    body: OfflineConversionDataRequestTypedDict


class IngestOfflineConversionDataRequest(BaseModel):
    ttd_auth: Annotated[
        str,
        pydantic.Field(alias="TTD-Auth"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Data API token for authentication."""

    body: Annotated[
        OfflineConversionDataRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class IngestOfflineConversionDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    offline_conversion_data_server_response: NotRequired[
        OfflineConversionDataServerResponseTypedDict
    ]
    r"""Success"""


class IngestOfflineConversionDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    offline_conversion_data_server_response: Optional[
        OfflineConversionDataServerResponse
    ] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["OfflineConversionDataServerResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
