"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .thirdpartydatarequest import ThirdPartyDataRequest, ThirdPartyDataRequestTypedDict
from .thirdpartydataserverresponse import (
    ThirdPartyDataServerResponse,
    ThirdPartyDataServerResponseTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from ttd_data.utils import FieldMetadata, HeaderMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


INGEST_THIRD_PARTY_DATA_OP_SERVERS = [
    "https://bulk-data.adsrvr.org",
]


class IngestThirdPartyDataRequestTypedDict(TypedDict):
    ttd_auth: str
    r"""Data API token for authentication."""
    body: ThirdPartyDataRequestTypedDict


class IngestThirdPartyDataRequest(BaseModel):
    ttd_auth: Annotated[
        str,
        pydantic.Field(alias="TTD-Auth"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Data API token for authentication."""

    body: Annotated[
        ThirdPartyDataRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class IngestThirdPartyDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    third_party_data_server_response: NotRequired[ThirdPartyDataServerResponseTypedDict]
    r"""Success"""


class IngestThirdPartyDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    third_party_data_server_response: Optional[ThirdPartyDataServerResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ThirdPartyDataServerResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
