"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 07f6600b6a46

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .ipaddressdatarequest import IPAddressDataRequest, IPAddressDataRequestTypedDict
from .ipaddressdataserverresponse import (
    IPAddressDataServerResponse,
    IPAddressDataServerResponseTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from ttd_data.utils import FieldMetadata, HeaderMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


INGEST_THIRD_PARTY_IP_ADDRESS_DATA_OP_SERVERS = [
    "https://usw-data.adsrvr.org",
]


class IngestThirdPartyIPAddressDataRequestTypedDict(TypedDict):
    ttd_auth: str
    r"""Data API token for authentication."""
    body: IPAddressDataRequestTypedDict


class IngestThirdPartyIPAddressDataRequest(BaseModel):
    ttd_auth: Annotated[
        str,
        pydantic.Field(alias="TTD-Auth"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Data API token for authentication."""

    body: Annotated[
        IPAddressDataRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class IngestThirdPartyIPAddressDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    ip_address_data_server_response: NotRequired[IPAddressDataServerResponseTypedDict]
    r"""Success"""


class IngestThirdPartyIPAddressDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    ip_address_data_server_response: Optional[IPAddressDataServerResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["IPAddressDataServerResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
