"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7b9550f1c695

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .thirdpartydataserverresponse import (
    ThirdPartyDataServerResponse,
    ThirdPartyDataServerResponseTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


INGEST_THIRD_PARTY_DATA_OP_SERVERS = [
    "https://bulk-data.adsrvr.org",
]


class IngestThirdPartyDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    third_party_data_server_response: NotRequired[ThirdPartyDataServerResponseTypedDict]
    r"""Success"""


class IngestThirdPartyDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    third_party_data_server_response: Optional[ThirdPartyDataServerResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ThirdPartyDataServerResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
