"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 3dff4f5ef0ef

from __future__ import annotations
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
from .offlineconversiondataserverresponse import (
    OfflineConversionDataServerResponse,
    OfflineConversionDataServerResponseTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


INGEST_OFFLINE_CONVERSION_DATA_OP_SERVERS = [
    "https://offlineattrib.adsrvr.org",
]


class IngestOfflineConversionDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    offline_conversion_data_server_response: NotRequired[
        OfflineConversionDataServerResponseTypedDict
    ]
    r"""Success"""


class IngestOfflineConversionDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    offline_conversion_data_server_response: Optional[
        OfflineConversionDataServerResponse
    ] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["OfflineConversionDataServerResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
