"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .advertiserdatarequest import AdvertiserDataRequest, AdvertiserDataRequestTypedDict
from .advertiserdataserverresponse import (
    AdvertiserDataServerResponse,
    AdvertiserDataServerResponseTypedDict,
)
from .httpmetadata import HTTPMetadata, HTTPMetadataTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, UNSET_SENTINEL
from ttd_data.utils import FieldMetadata, HeaderMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


INGEST_ADVERTISER_DATA_OP_SERVERS = [
    "https://usw-data.adsrvr.org",
]


class IngestAdvertiserDataRequestTypedDict(TypedDict):
    ttd_auth: str
    r"""Data API token for authentication."""
    body: AdvertiserDataRequestTypedDict


class IngestAdvertiserDataRequest(BaseModel):
    ttd_auth: Annotated[
        str,
        pydantic.Field(alias="TTD-Auth"),
        FieldMetadata(header=HeaderMetadata(style="simple", explode=False)),
    ]
    r"""Data API token for authentication."""

    body: Annotated[
        AdvertiserDataRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class IngestAdvertiserDataResponseTypedDict(TypedDict):
    http_meta: HTTPMetadataTypedDict
    advertiser_data_server_response: NotRequired[AdvertiserDataServerResponseTypedDict]
    r"""Success"""


class IngestAdvertiserDataResponse(BaseModel):
    http_meta: Annotated[Optional[HTTPMetadata], pydantic.Field(exclude=True)] = None

    advertiser_data_server_response: Optional[AdvertiserDataServerResponse] = None
    r"""Success"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["AdvertiserDataServerResponse"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
