"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 0caae65b4521

from __future__ import annotations
from .ipaddressdataitem import IPAddressDataItem, IPAddressDataItemTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class IPAddressDataRequestTypedDict(TypedDict):
    data_owner_id: str
    items: NotRequired[Nullable[List[IPAddressDataItemTypedDict]]]
    data_load_trace_id: NotRequired[Nullable[str]]


class IPAddressDataRequest(BaseModel):
    data_owner_id: Annotated[str, pydantic.Field(alias="DataOwnerId")]

    items: Annotated[
        OptionalNullable[List[IPAddressDataItem]], pydantic.Field(alias="Items")
    ] = UNSET

    data_load_trace_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataLoadTraceId")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Items", "DataLoadTraceId"])
        nullable_fields = set(["Items", "DataLoadTraceId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    IPAddressDataRequest.model_rebuild()
except NameError:
    pass
