"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: d8b6cc367879

from __future__ import annotations
from .ipaddressdataresponseerrorcode import IPAddressDataResponseErrorCode
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class IPAddressDataServerResponseLineTypedDict(TypedDict):
    data_name: NotRequired[Nullable[str]]
    error_code: NotRequired[IPAddressDataResponseErrorCode]
    ip_address: NotRequired[Nullable[str]]
    message: NotRequired[Nullable[str]]
    item_number: NotRequired[Nullable[str]]
    data_number: NotRequired[Nullable[str]]


class IPAddressDataServerResponseLine(BaseModel):
    data_name: Annotated[OptionalNullable[str], pydantic.Field(alias="DataName")] = (
        UNSET
    )

    error_code: Annotated[
        Optional[IPAddressDataResponseErrorCode], pydantic.Field(alias="ErrorCode")
    ] = None

    ip_address: Annotated[OptionalNullable[str], pydantic.Field(alias="IPAddress")] = (
        UNSET
    )

    message: Annotated[OptionalNullable[str], pydantic.Field(alias="Message")] = UNSET

    item_number: Annotated[
        OptionalNullable[str], pydantic.Field(alias="ItemNumber")
    ] = UNSET

    data_number: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataNumber")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "DataName",
                "ErrorCode",
                "IPAddress",
                "Message",
                "ItemNumber",
                "DataNumber",
            ]
        )
        nullable_fields = set(
            ["DataName", "IPAddress", "Message", "ItemNumber", "DataNumber"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    IPAddressDataServerResponseLine.model_rebuild()
except NameError:
    pass
