"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 184daceb940e

from __future__ import annotations
from .ipaddressdataserverresponseline import (
    IPAddressDataServerResponseLine,
    IPAddressDataServerResponseLineTypedDict,
)
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class IPAddressDataServerResponseTypedDict(TypedDict):
    data_owner_id: NotRequired[Nullable[str]]
    failed_lines: NotRequired[Nullable[List[IPAddressDataServerResponseLineTypedDict]]]


class IPAddressDataServerResponse(BaseModel):
    data_owner_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataOwnerId")
    ] = UNSET

    failed_lines: Annotated[
        OptionalNullable[List[IPAddressDataServerResponseLine]],
        pydantic.Field(alias="FailedLines"),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["DataOwnerId", "FailedLines"])
        nullable_fields = set(["DataOwnerId", "FailedLines"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    IPAddressDataServerResponse.model_rebuild()
except NameError:
    pass
