"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 1cb39b7876ab

from __future__ import annotations
from .expandedipaddress import ExpandedIPAddress, ExpandedIPAddressTypedDict
from datetime import datetime
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class IPAddressDataTypedDict(TypedDict):
    name: str
    timestamp_utc: NotRequired[Nullable[datetime]]
    ttl_in_minutes: NotRequired[Nullable[int]]
    targeting_data_metadata_id: NotRequired[Nullable[int]]
    ip_addresses: NotRequired[Nullable[List[str]]]
    ip_address_ranges: NotRequired[Nullable[List[str]]]
    expanded_ip_addresses: NotRequired[Nullable[List[ExpandedIPAddressTypedDict]]]


class IPAddressData(BaseModel):
    name: Annotated[str, pydantic.Field(alias="Name")]

    timestamp_utc: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="TimestampUtc")
    ] = UNSET

    ttl_in_minutes: Annotated[
        OptionalNullable[int], pydantic.Field(alias="TtlInMinutes")
    ] = UNSET

    targeting_data_metadata_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="TargetingDataMetadataId")
    ] = UNSET

    ip_addresses: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="IPAddresses")
    ] = UNSET

    ip_address_ranges: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="IPAddressRanges")
    ] = UNSET

    expanded_ip_addresses: Annotated[
        OptionalNullable[List[ExpandedIPAddress]],
        pydantic.Field(alias="ExpandedIpAddresses"),
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "TimestampUtc",
                "TtlInMinutes",
                "TargetingDataMetadataId",
                "IPAddresses",
                "IPAddressRanges",
                "ExpandedIpAddresses",
            ]
        )
        nullable_fields = set(
            [
                "TimestampUtc",
                "TtlInMinutes",
                "TargetingDataMetadataId",
                "IPAddresses",
                "IPAddressRanges",
                "ExpandedIpAddresses",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    IPAddressData.model_rebuild()
except NameError:
    pass
