"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 53204601212d

from __future__ import annotations
from enum import Enum


class IPAddressDataResponseErrorCode(str, Enum):
    UNKNOWN = "Unknown"
    MISSING_DATA_OWNER_ID = "MissingDataOwnerId"
    DATA_OWNER_ID_NOT_MAPPED = "DataOwnerIdNotMapped"
    INVALID_IP_ADDRESS = "InvalidIPAddress"
    INVALID_IP_ADDRESS_RANGE = "InvalidIPAddressRange"
    EU_IP_TARGETING_NOT_ALLOWED_FOR_PARTNER = "EuIpTargetingNotAllowedForPartner"
    NOT_TARGETABLE = "NotTargetable"
