"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 4f8f69a30b61

from __future__ import annotations
from .partnerdsrdataitem import PartnerDsrDataItem, PartnerDsrDataItemTypedDict
from .partnerdsrrequesttype import PartnerDsrRequestType
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class MerchantDsrRequestTypedDict(TypedDict):
    merchant_id: NotRequired[Nullable[int]]
    items: NotRequired[Nullable[List[PartnerDsrDataItemTypedDict]]]
    data_load_trace_id: NotRequired[Nullable[str]]
    request_type: NotRequired[PartnerDsrRequestType]


class MerchantDsrRequest(BaseModel):
    merchant_id: Annotated[
        OptionalNullable[int], pydantic.Field(alias="MerchantId")
    ] = UNSET

    items: Annotated[
        OptionalNullable[List[PartnerDsrDataItem]], pydantic.Field(alias="Items")
    ] = UNSET

    data_load_trace_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataLoadTraceId")
    ] = UNSET

    request_type: Annotated[
        Optional[PartnerDsrRequestType], pydantic.Field(alias="RequestType")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["MerchantId", "Items", "DataLoadTraceId", "RequestType"])
        nullable_fields = set(["MerchantId", "Items", "DataLoadTraceId"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    MerchantDsrRequest.model_rebuild()
except NameError:
    pass
