"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: e10b97e7f07c

from __future__ import annotations
from enum import Enum


class OfflineConversionDataResponseErrorCode(str, Enum):
    UNKNOWN = "Unknown"
    MISSING_OR_INVALID_TDID_AND_IMPRESSION_ID = "MissingOrInvalidTDIDAndImpressionId"
    MISSING_OR_INVALID_TRACKING_TAG_ID = "MissingOrInvalidTrackingTagId"
    INVALID_MERCHANT_ID = "InvalidMerchantId"
    CHINA_PII = "ChinaPII"
    INVALID_TIMESTAMP = "InvalidTimestamp"
    INVALID_USER_ID_TYPE_OR_USER_ID = "InvalidUserIdTypeOrUserId"
    UNAUTHORIZED = "Unauthorized"
