"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7d81245ab1fc

from __future__ import annotations
from ._baseofflineconversiondataitem import (
    BaseOfflineConversionDataItem,
    BaseOfflineConversionDataItemTypedDict,
)
from .dataorigin import DataOrigin, DataOriginTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class OfflineConversionDataRequestTypedDict(TypedDict):
    data_provider_id: str
    user_id_array_metadata_format: NotRequired[Nullable[List[str]]]
    items: NotRequired[Nullable[List[BaseOfflineConversionDataItemTypedDict]]]
    data_load_trace_id: NotRequired[Nullable[str]]
    data_origins: NotRequired[Nullable[List[DataOriginTypedDict]]]


class OfflineConversionDataRequest(BaseModel):
    data_provider_id: Annotated[str, pydantic.Field(alias="DataProviderId")]

    user_id_array_metadata_format: Annotated[
        OptionalNullable[List[str]], pydantic.Field(alias="UserIdArrayMetadataFormat")
    ] = UNSET

    items: Annotated[
        OptionalNullable[List[BaseOfflineConversionDataItem]],
        pydantic.Field(alias="Items"),
    ] = UNSET

    data_load_trace_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataLoadTraceId")
    ] = UNSET

    data_origins: Annotated[
        OptionalNullable[List[DataOrigin]], pydantic.Field(alias="DataOrigins")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["UserIdArrayMetadataFormat", "Items", "DataLoadTraceId", "DataOrigins"]
        )
        nullable_fields = set(
            ["UserIdArrayMetadataFormat", "Items", "DataLoadTraceId", "DataOrigins"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    OfflineConversionDataRequest.model_rebuild()
except NameError:
    pass
