"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 3f36747f69ac

from __future__ import annotations
from .baseofflineconversiondataitem import (
    BaseOfflineConversionDataItem,
    BaseOfflineConversionDataItemTypedDict,
)
from .offlineconversiondataresponseerrorcode import (
    OfflineConversionDataResponseErrorCode,
)
from datetime import datetime
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class OfflineConversionDataServerResponseLineTypedDict(TypedDict):
    order_id: NotRequired[Nullable[str]]
    impression_id: NotRequired[Nullable[str]]
    tdid: NotRequired[Nullable[str]]
    tracking_tag_id: NotRequired[Nullable[str]]
    timestamp_utc: NotRequired[datetime]
    error_code: NotRequired[OfflineConversionDataResponseErrorCode]
    message: NotRequired[Nullable[str]]
    item_number: NotRequired[Nullable[str]]
    original_request: NotRequired[BaseOfflineConversionDataItemTypedDict]


class OfflineConversionDataServerResponseLine(BaseModel):
    order_id: Annotated[OptionalNullable[str], pydantic.Field(alias="OrderId")] = UNSET

    impression_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="ImpressionId")
    ] = UNSET

    tdid: Annotated[OptionalNullable[str], pydantic.Field(alias="TDID")] = UNSET

    tracking_tag_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="TrackingTagId")
    ] = UNSET

    timestamp_utc: Annotated[
        Optional[datetime], pydantic.Field(alias="TimestampUtc")
    ] = None

    error_code: Annotated[
        Optional[OfflineConversionDataResponseErrorCode],
        pydantic.Field(alias="ErrorCode"),
    ] = None

    message: Annotated[OptionalNullable[str], pydantic.Field(alias="Message")] = UNSET

    item_number: Annotated[
        OptionalNullable[str], pydantic.Field(alias="ItemNumber")
    ] = UNSET

    original_request: Annotated[
        Optional[BaseOfflineConversionDataItem], pydantic.Field(alias="OriginalRequest")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "OrderId",
                "ImpressionId",
                "TDID",
                "TrackingTagId",
                "TimestampUtc",
                "ErrorCode",
                "Message",
                "ItemNumber",
                "OriginalRequest",
            ]
        )
        nullable_fields = set(
            [
                "OrderId",
                "ImpressionId",
                "TDID",
                "TrackingTagId",
                "Message",
                "ItemNumber",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    OfflineConversionDataServerResponseLine.model_rebuild()
except NameError:
    pass
