"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: cac9dd97133a

from __future__ import annotations
from enum import Enum


class PartnerDsrRequestType(str, Enum):
    OPT_OUT = "OptOut"
    DELETION = "Deletion"
