"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing_extensions import NotRequired, TypedDict


class RealTimeConversionEventLineItemTypedDict(TypedDict):
    item_code: NotRequired[Nullable[str]]
    name: NotRequired[Nullable[str]]
    qty: NotRequired[Nullable[str]]
    price: NotRequired[Nullable[str]]
    cat: NotRequired[Nullable[str]]


class RealTimeConversionEventLineItem(BaseModel):
    item_code: OptionalNullable[str] = UNSET

    name: OptionalNullable[str] = UNSET

    qty: OptionalNullable[str] = UNSET

    price: OptionalNullable[str] = UNSET

    cat: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["item_code", "name", "qty", "price", "cat"])
        nullable_fields = set(["item_code", "name", "qty", "price", "cat"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
