"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing_extensions import Annotated, NotRequired, TypedDict


class StringStringValueTupleTypedDict(TypedDict):
    item1: NotRequired[Nullable[str]]
    item2: NotRequired[Nullable[str]]


class StringStringValueTuple(BaseModel):
    item1: Annotated[OptionalNullable[str], pydantic.Field(alias="Item1")] = UNSET

    item2: Annotated[OptionalNullable[str], pydantic.Field(alias="Item2")] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Item1", "Item2"])
        nullable_fields = set(["Item1", "Item2"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    StringStringValueTuple.model_rebuild()
except NameError:
    pass
