"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .thirdpartydataresponseerrorcode import ThirdPartyDataResponseErrorCode
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ThirdPartyDataServerResponseLineTypedDict(TypedDict):
    data_provider_user_id: NotRequired[Nullable[str]]
    tdid: NotRequired[Nullable[str]]
    error_code: NotRequired[ThirdPartyDataResponseErrorCode]
    message: NotRequired[Nullable[str]]
    data_name: NotRequired[Nullable[str]]


class ThirdPartyDataServerResponseLine(BaseModel):
    data_provider_user_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataProviderUserId")
    ] = UNSET

    tdid: Annotated[OptionalNullable[str], pydantic.Field(alias="TDID")] = UNSET

    error_code: Annotated[
        Optional[ThirdPartyDataResponseErrorCode], pydantic.Field(alias="ErrorCode")
    ] = None

    message: Annotated[OptionalNullable[str], pydantic.Field(alias="Message")] = UNSET

    data_name: Annotated[OptionalNullable[str], pydantic.Field(alias="DataName")] = (
        UNSET
    )

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["DataProviderUserId", "TDID", "ErrorCode", "Message", "DataName"]
        )
        nullable_fields = set(["DataProviderUserId", "TDID", "Message", "DataName"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ThirdPartyDataServerResponseLine.model_rebuild()
except NameError:
    pass
