"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing_extensions import Annotated, NotRequired, TypedDict


class ThirdPartyDataTypedDict(TypedDict):
    name: str
    timestamp_utc: NotRequired[Nullable[datetime]]
    ttl_in_minutes: NotRequired[Nullable[int]]


class ThirdPartyData(BaseModel):
    name: Annotated[str, pydantic.Field(alias="Name")]

    timestamp_utc: Annotated[
        OptionalNullable[datetime], pydantic.Field(alias="TimestampUtc")
    ] = UNSET

    ttl_in_minutes: Annotated[
        OptionalNullable[int], pydantic.Field(alias="TtlInMinutes")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["TimestampUtc", "TtlInMinutes"])
        nullable_fields = set(["TimestampUtc", "TtlInMinutes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ThirdPartyData.model_rebuild()
except NameError:
    pass
