"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: c79166cc6728

from __future__ import annotations
from enum import Enum


class ThirdPartyDataResponseErrorCode(str, Enum):
    UNKNOWN = "Unknown"
    MISSING_USER_ID = "MissingUserId"
    USER_NOT_MAPPED = "UserNotMapped"
    DATA_NAME_TOO_LONG = "DataNameTooLong"
    UNAUTHORISED_THIRD_PARTY_DATA_WITH_BASE_BID_CPM = (
        "UnauthorisedThirdPartyDataWithBaseBidCPM"
    )
    INVALID_TTL_IN_MINUTES = "InvalidTtlInMinutes"
