"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .thirdpartydataitem import ThirdPartyDataItem, ThirdPartyDataItemTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ThirdPartyDataRequestTypedDict(TypedDict):
    data_provider_id: str
    items: NotRequired[Nullable[List[ThirdPartyDataItemTypedDict]]]
    is_user_id_already_hashed: NotRequired[bool]


class ThirdPartyDataRequest(BaseModel):
    data_provider_id: Annotated[str, pydantic.Field(alias="DataProviderId")]

    items: Annotated[
        OptionalNullable[List[ThirdPartyDataItem]], pydantic.Field(alias="Items")
    ] = UNSET

    is_user_id_already_hashed: Annotated[
        Optional[bool], pydantic.Field(alias="IsUserIdAlreadyHashed")
    ] = False

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["Items", "IsUserIdAlreadyHashed"])
        nullable_fields = set(["Items"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ThirdPartyDataRequest.model_rebuild()
except NameError:
    pass
