"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .partnerdsrdataitem import PartnerDsrDataItem, PartnerDsrDataItemTypedDict
from .partnerdsrrequesttype import PartnerDsrRequestType
import pydantic
from pydantic import model_serializer
from ttd_data.types import BaseModel, Nullable, OptionalNullable, UNSET, UNSET_SENTINEL
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ThirdPartyDsrRequestTypedDict(TypedDict):
    data_provider_id: NotRequired[Nullable[str]]
    brand_id: NotRequired[Nullable[str]]
    items: NotRequired[Nullable[List[PartnerDsrDataItemTypedDict]]]
    request_type: NotRequired[PartnerDsrRequestType]


class ThirdPartyDsrRequest(BaseModel):
    data_provider_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="DataProviderId")
    ] = UNSET

    brand_id: Annotated[OptionalNullable[str], pydantic.Field(alias="BrandId")] = UNSET

    items: Annotated[
        OptionalNullable[List[PartnerDsrDataItem]], pydantic.Field(alias="Items")
    ] = UNSET

    request_type: Annotated[
        Optional[PartnerDsrRequestType], pydantic.Field(alias="RequestType")
    ] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["DataProviderId", "BrandId", "Items", "RequestType"])
        nullable_fields = set(["DataProviderId", "BrandId", "Items"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


try:
    ThirdPartyDsrRequest.model_rebuild()
except NameError:
    pass
