"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 48aae23daf2a

from ._version import (
    __title__,
    __version__,
    __openapi_doc_version__,
    __gen_version__,
    __user_agent__,
)
from .sdkconfiguration import *
# region: Manually edited code section
# pylint: disable=useless-import-alias
from .client import DataClient as DataClient
from .uid2 import (
    IdentityScope as IdentityScope,
    UID2Config as UID2Config,
    UID2ServiceError as UID2ServiceError,
    UserIdType as UserIdType,
)
# endregion: Manually edited code section


VERSION: str = __version__
OPENAPI_DOC_VERSION = __openapi_doc_version__
SPEAKEASY_GENERATOR_VERSION = __gen_version__
USER_AGENT = __user_agent__
