"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

import importlib.metadata

__title__: str = "ttd-data"
__version__: str = "0.1.4"
__openapi_doc_version__: str = "v0.1"
__gen_version__: str = "2.866.2"
__user_agent__: str = "speakeasy-sdk/python 0.1.4 2.866.2 v0.1 ttd-data"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
