"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 7feb4586507e

import importlib.metadata

__title__: str = "ttd-data"
__version__: str = "0.2.3"
__openapi_doc_version__: str = "v0.1"
__gen_version__: str = "2.893.0"
__user_agent__: str = "speakeasy-sdk/python 0.2.3 2.893.0 v0.1 ttd-data"

try:
    if __package__ is not None:
        __version__ = importlib.metadata.version(__package__)
except importlib.metadata.PackageNotFoundError:
    pass
