"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""
# @generated-id: 8da72b51c89e

from .basesdk import BaseSDK
from ttd_data import errors, models, utils
from ttd_data._hooks import HookContext
from ttd_data.types import OptionalNullable, UNSET
from ttd_data.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, Iterable, List, Mapping, Optional, Union


class DeletionOptOut(BaseSDK):
    def data_subject_request_advertiser_data(
        self,
        *,
        ttd_auth: str,
        advertiser_id: OptionalNullable[str] = UNSET,
        data_provider_id: OptionalNullable[str] = UNSET,
        items: OptionalNullable[
            Union[
                Iterable[models.BasePartnerDsrDataItem],
                Iterable[models.BasePartnerDsrDataItemTypedDict],
            ]
        ] = UNSET,
        data_load_trace_id: OptionalNullable[str] = UNSET,
        request_type: Optional[models.PartnerDsrRequestType] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DataSubjectRequestAdvertiserDataResponse:
        r"""Delete IDs shared with The Trade Desk for the specified advertiser ID.

        :param ttd_auth: Data API token for authentication.
        :param advertiser_id:
        :param data_provider_id:
        :param items:
        :param data_load_trace_id:
        :param request_type:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.DATA_SUBJECT_REQUEST_ADVERTISER_DATA_OP_SERVERS[0]

        request = models.DataSubjectRequestAdvertiserDataRequest(
            ttd_auth=ttd_auth,
            body=models.AdvertiserDsrRequest(
                advertiser_id=advertiser_id,
                data_provider_id=data_provider_id,
                items=utils.get_pydantic_model(
                    items, OptionalNullable[List[models.BasePartnerDsrDataItem]]
                ),
                data_load_trace_id=data_load_trace_id,
                request_type=request_type,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/data/deletion-optout/advertiser",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.AdvertiserDsrRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DataSubjectRequestAdvertiserData",
                oauth2_scopes=None,
                security_source=None,
                tags=["DeletionOptOut"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.DataSubjectRequestAdvertiserDataResponse(
                advertiser_dsr_response=unmarshal_json_response(
                    Optional[models.AdvertiserDsrResponse], http_res
                ),
                http_meta=models.HTTPMetadata(request=req, response=http_res),
            )
        if utils.match_response(http_res, ["400", "429"], "application/json"):
            response_data = unmarshal_json_response(
                errors.AdvertiserDsrResponseErrorData, http_res
            )
            response_data.http_meta = models.HTTPMetadata(
                request=req, response=http_res
            )
            raise errors.AdvertiserDsrResponseError(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "413", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def data_subject_request_advertiser_data_async(
        self,
        *,
        ttd_auth: str,
        advertiser_id: OptionalNullable[str] = UNSET,
        data_provider_id: OptionalNullable[str] = UNSET,
        items: OptionalNullable[
            Union[
                Iterable[models.BasePartnerDsrDataItem],
                Iterable[models.BasePartnerDsrDataItemTypedDict],
            ]
        ] = UNSET,
        data_load_trace_id: OptionalNullable[str] = UNSET,
        request_type: Optional[models.PartnerDsrRequestType] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DataSubjectRequestAdvertiserDataResponse:
        r"""Delete IDs shared with The Trade Desk for the specified advertiser ID.

        :param ttd_auth: Data API token for authentication.
        :param advertiser_id:
        :param data_provider_id:
        :param items:
        :param data_load_trace_id:
        :param request_type:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.DATA_SUBJECT_REQUEST_ADVERTISER_DATA_OP_SERVERS[0]

        request = models.DataSubjectRequestAdvertiserDataRequest(
            ttd_auth=ttd_auth,
            body=models.AdvertiserDsrRequest(
                advertiser_id=advertiser_id,
                data_provider_id=data_provider_id,
                items=utils.get_pydantic_model(
                    items, OptionalNullable[List[models.BasePartnerDsrDataItem]]
                ),
                data_load_trace_id=data_load_trace_id,
                request_type=request_type,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/data/deletion-optout/advertiser",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.AdvertiserDsrRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DataSubjectRequestAdvertiserData",
                oauth2_scopes=None,
                security_source=None,
                tags=["DeletionOptOut"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.DataSubjectRequestAdvertiserDataResponse(
                advertiser_dsr_response=unmarshal_json_response(
                    Optional[models.AdvertiserDsrResponse], http_res
                ),
                http_meta=models.HTTPMetadata(request=req, response=http_res),
            )
        if utils.match_response(http_res, ["400", "429"], "application/json"):
            response_data = unmarshal_json_response(
                errors.AdvertiserDsrResponseErrorData, http_res
            )
            response_data.http_meta = models.HTTPMetadata(
                request=req, response=http_res
            )
            raise errors.AdvertiserDsrResponseError(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "413", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def data_subject_request_merchant_data(
        self,
        *,
        ttd_auth: str,
        merchant_id: OptionalNullable[int] = UNSET,
        items: OptionalNullable[
            Union[
                Iterable[models.BasePartnerDsrDataItem],
                Iterable[models.BasePartnerDsrDataItemTypedDict],
            ]
        ] = UNSET,
        data_load_trace_id: OptionalNullable[str] = UNSET,
        request_type: Optional[models.PartnerDsrRequestType] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DataSubjectRequestMerchantDataResponse:
        r"""Delete IDs shared with The Trade Desk via a product catalog for the specified merchant ID.

        :param ttd_auth: Data API token for authentication.
        :param merchant_id:
        :param items:
        :param data_load_trace_id:
        :param request_type:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.DATA_SUBJECT_REQUEST_MERCHANT_DATA_OP_SERVERS[0]

        request = models.DataSubjectRequestMerchantDataRequest(
            ttd_auth=ttd_auth,
            body=models.MerchantDsrRequest(
                merchant_id=merchant_id,
                items=utils.get_pydantic_model(
                    items, OptionalNullable[List[models.BasePartnerDsrDataItem]]
                ),
                data_load_trace_id=data_load_trace_id,
                request_type=request_type,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/data/deletion-optout/merchant",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.MerchantDsrRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DataSubjectRequestMerchantData",
                oauth2_scopes=None,
                security_source=None,
                tags=["DeletionOptOut"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.DataSubjectRequestMerchantDataResponse(
                merchant_dsr_response=unmarshal_json_response(
                    Optional[models.MerchantDsrResponse], http_res
                ),
                http_meta=models.HTTPMetadata(request=req, response=http_res),
            )
        if utils.match_response(http_res, ["400", "429"], "application/json"):
            response_data = unmarshal_json_response(
                errors.MerchantDsrResponseErrorData, http_res
            )
            response_data.http_meta = models.HTTPMetadata(
                request=req, response=http_res
            )
            raise errors.MerchantDsrResponseError(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "413", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def data_subject_request_merchant_data_async(
        self,
        *,
        ttd_auth: str,
        merchant_id: OptionalNullable[int] = UNSET,
        items: OptionalNullable[
            Union[
                Iterable[models.BasePartnerDsrDataItem],
                Iterable[models.BasePartnerDsrDataItemTypedDict],
            ]
        ] = UNSET,
        data_load_trace_id: OptionalNullable[str] = UNSET,
        request_type: Optional[models.PartnerDsrRequestType] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DataSubjectRequestMerchantDataResponse:
        r"""Delete IDs shared with The Trade Desk via a product catalog for the specified merchant ID.

        :param ttd_auth: Data API token for authentication.
        :param merchant_id:
        :param items:
        :param data_load_trace_id:
        :param request_type:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.DATA_SUBJECT_REQUEST_MERCHANT_DATA_OP_SERVERS[0]

        request = models.DataSubjectRequestMerchantDataRequest(
            ttd_auth=ttd_auth,
            body=models.MerchantDsrRequest(
                merchant_id=merchant_id,
                items=utils.get_pydantic_model(
                    items, OptionalNullable[List[models.BasePartnerDsrDataItem]]
                ),
                data_load_trace_id=data_load_trace_id,
                request_type=request_type,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/data/deletion-optout/merchant",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.MerchantDsrRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DataSubjectRequestMerchantData",
                oauth2_scopes=None,
                security_source=None,
                tags=["DeletionOptOut"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.DataSubjectRequestMerchantDataResponse(
                merchant_dsr_response=unmarshal_json_response(
                    Optional[models.MerchantDsrResponse], http_res
                ),
                http_meta=models.HTTPMetadata(request=req, response=http_res),
            )
        if utils.match_response(http_res, ["400", "429"], "application/json"):
            response_data = unmarshal_json_response(
                errors.MerchantDsrResponseErrorData, http_res
            )
            response_data.http_meta = models.HTTPMetadata(
                request=req, response=http_res
            )
            raise errors.MerchantDsrResponseError(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "413", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    def data_subject_request_third_party_data(
        self,
        *,
        ttd_auth: str,
        data_provider_id: OptionalNullable[str] = UNSET,
        brand_id: OptionalNullable[str] = UNSET,
        items: OptionalNullable[
            Union[
                Iterable[models.BasePartnerDsrDataItem],
                Iterable[models.BasePartnerDsrDataItemTypedDict],
            ]
        ] = UNSET,
        data_load_trace_id: OptionalNullable[str] = UNSET,
        request_type: Optional[models.PartnerDsrRequestType] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DataSubjectRequestThirdPartyDataResponse:
        r"""Delete IDs shared with The Trade Desk for the specified data provider ID.

        :param ttd_auth: Data API token for authentication.
        :param data_provider_id:
        :param brand_id:
        :param items:
        :param data_load_trace_id:
        :param request_type:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.DATA_SUBJECT_REQUEST_THIRD_PARTY_DATA_OP_SERVERS[0]

        request = models.DataSubjectRequestThirdPartyDataRequest(
            ttd_auth=ttd_auth,
            body=models.ThirdPartyDsrRequest(
                data_provider_id=data_provider_id,
                brand_id=brand_id,
                items=utils.get_pydantic_model(
                    items, OptionalNullable[List[models.BasePartnerDsrDataItem]]
                ),
                data_load_trace_id=data_load_trace_id,
                request_type=request_type,
            ),
        )

        req = self._build_request(
            method="POST",
            path="/data/deletion-optout/thirdparty",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.ThirdPartyDsrRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DataSubjectRequestThirdPartyData",
                oauth2_scopes=None,
                security_source=None,
                tags=["DeletionOptOut"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.DataSubjectRequestThirdPartyDataResponse(
                third_party_dsr_response=unmarshal_json_response(
                    Optional[models.ThirdPartyDsrResponse], http_res
                ),
                http_meta=models.HTTPMetadata(request=req, response=http_res),
            )
        if utils.match_response(http_res, ["400", "429"], "application/json"):
            response_data = unmarshal_json_response(
                errors.ThirdPartyDsrResponseErrorData, http_res
            )
            response_data.http_meta = models.HTTPMetadata(
                request=req, response=http_res
            )
            raise errors.ThirdPartyDsrResponseError(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "413", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def data_subject_request_third_party_data_async(
        self,
        *,
        ttd_auth: str,
        data_provider_id: OptionalNullable[str] = UNSET,
        brand_id: OptionalNullable[str] = UNSET,
        items: OptionalNullable[
            Union[
                Iterable[models.BasePartnerDsrDataItem],
                Iterable[models.BasePartnerDsrDataItemTypedDict],
            ]
        ] = UNSET,
        data_load_trace_id: OptionalNullable[str] = UNSET,
        request_type: Optional[models.PartnerDsrRequestType] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.DataSubjectRequestThirdPartyDataResponse:
        r"""Delete IDs shared with The Trade Desk for the specified data provider ID.

        :param ttd_auth: Data API token for authentication.
        :param data_provider_id:
        :param brand_id:
        :param items:
        :param data_load_trace_id:
        :param request_type:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.DATA_SUBJECT_REQUEST_THIRD_PARTY_DATA_OP_SERVERS[0]

        request = models.DataSubjectRequestThirdPartyDataRequest(
            ttd_auth=ttd_auth,
            body=models.ThirdPartyDsrRequest(
                data_provider_id=data_provider_id,
                brand_id=brand_id,
                items=utils.get_pydantic_model(
                    items, OptionalNullable[List[models.BasePartnerDsrDataItem]]
                ),
                data_load_trace_id=data_load_trace_id,
                request_type=request_type,
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/data/deletion-optout/thirdparty",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.ThirdPartyDsrRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="DataSubjectRequestThirdPartyData",
                oauth2_scopes=None,
                security_source=None,
                tags=["DeletionOptOut"],
                extensions=None,
            ),
            request=req,
            is_error_status_code=lambda c: utils.match_status_codes(["4XX", "5XX"], c),
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.DataSubjectRequestThirdPartyDataResponse(
                third_party_dsr_response=unmarshal_json_response(
                    Optional[models.ThirdPartyDsrResponse], http_res
                ),
                http_meta=models.HTTPMetadata(request=req, response=http_res),
            )
        if utils.match_response(http_res, ["400", "429"], "application/json"):
            response_data = unmarshal_json_response(
                errors.ThirdPartyDsrResponseErrorData, http_res
            )
            response_data.http_meta = models.HTTPMetadata(
                request=req, response=http_res
            )
            raise errors.ThirdPartyDsrResponseError(response_data, http_res)
        if utils.match_response(http_res, ["401", "403", "413", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)
