"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from ttd_data import errors, models, utils
from ttd_data._hooks import HookContext
from ttd_data.types import OptionalNullable, UNSET
from ttd_data.utils.unmarshal_json_response import unmarshal_json_response
from typing import Any, List, Mapping, Optional, Union


class OfflineConversion(BaseSDK):
    def ingest_offline_conversion_data(
        self,
        *,
        ttd_auth: str,
        data_provider_id: str,
        user_id_array_metadata_format: OptionalNullable[List[str]] = UNSET,
        items: OptionalNullable[
            Union[
                List[models.OfflineConversionDataItem],
                List[models.OfflineConversionDataItemTypedDict],
            ]
        ] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.IngestOfflineConversionDataResponse:
        r"""Upload offline conversion data for the specified data provider.

        :param ttd_auth: Data API token for authentication.
        :param data_provider_id:
        :param user_id_array_metadata_format:
        :param items:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.INGEST_OFFLINE_CONVERSION_DATA_OP_SERVERS[0]

        request = models.IngestOfflineConversionDataRequest(
            ttd_auth=ttd_auth,
            body=models.OfflineConversionDataRequest(
                data_provider_id=data_provider_id,
                user_id_array_metadata_format=user_id_array_metadata_format,
                items=utils.get_pydantic_model(
                    items, OptionalNullable[List[models.OfflineConversionDataItem]]
                ),
            ),
        )

        req = self._build_request(
            method="POST",
            path="/providerapi/offlineconversion",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.OfflineConversionDataRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="IngestOfflineConversionData",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "403", "413", "429", "4XX", "500", "503", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.IngestOfflineConversionDataResponse(
                offline_conversion_data_server_response=unmarshal_json_response(
                    Optional[models.OfflineConversionDataServerResponse], http_res
                ),
                http_meta=models.HTTPMetadata(request=req, response=http_res),
            )
        if utils.match_response(http_res, ["400", "429"], "application/json"):
            response_data = unmarshal_json_response(
                errors.OfflineConversionDataServerResponseErrorData, http_res
            )
            response_data.http_meta = models.HTTPMetadata(
                request=req, response=http_res
            )
            raise errors.OfflineConversionDataServerResponseError(
                response_data, http_res
            )
        if utils.match_response(http_res, ["403", "413", "4XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)

    async def ingest_offline_conversion_data_async(
        self,
        *,
        ttd_auth: str,
        data_provider_id: str,
        user_id_array_metadata_format: OptionalNullable[List[str]] = UNSET,
        items: OptionalNullable[
            Union[
                List[models.OfflineConversionDataItem],
                List[models.OfflineConversionDataItemTypedDict],
            ]
        ] = UNSET,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> models.IngestOfflineConversionDataResponse:
        r"""Upload offline conversion data for the specified data provider.

        :param ttd_auth: Data API token for authentication.
        :param data_provider_id:
        :param user_id_array_metadata_format:
        :param items:
        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = models.INGEST_OFFLINE_CONVERSION_DATA_OP_SERVERS[0]

        request = models.IngestOfflineConversionDataRequest(
            ttd_auth=ttd_auth,
            body=models.OfflineConversionDataRequest(
                data_provider_id=data_provider_id,
                user_id_array_metadata_format=user_id_array_metadata_format,
                items=utils.get_pydantic_model(
                    items, OptionalNullable[List[models.OfflineConversionDataItem]]
                ),
            ),
        )

        req = self._build_request_async(
            method="POST",
            path="/providerapi/offlineconversion",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=True,
            request_has_path_params=False,
            request_has_query_params=False,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            get_serialized_body=lambda: utils.serialize_request_body(
                request.body, False, False, "json", models.OfflineConversionDataRequest
            ),
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="IngestOfflineConversionData",
                oauth2_scopes=None,
                security_source=None,
            ),
            request=req,
            error_status_codes=["400", "403", "413", "429", "4XX", "500", "503", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return models.IngestOfflineConversionDataResponse(
                offline_conversion_data_server_response=unmarshal_json_response(
                    Optional[models.OfflineConversionDataServerResponse], http_res
                ),
                http_meta=models.HTTPMetadata(request=req, response=http_res),
            )
        if utils.match_response(http_res, ["400", "429"], "application/json"):
            response_data = unmarshal_json_response(
                errors.OfflineConversionDataServerResponseErrorData, http_res
            )
            response_data.http_meta = models.HTTPMetadata(
                request=req, response=http_res
            )
            raise errors.OfflineConversionDataServerResponseError(
                response_data, http_res
            )
        if utils.match_response(http_res, ["403", "413", "4XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, ["500", "503", "5XX"], "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise errors.APIError("API error occurred", http_res, http_res_text)

        raise errors.APIError("Unexpected response received", http_res)
