"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .advertiserdata import AdvertiserData, AdvertiserDataTypedDict
import pydantic
from pydantic import model_serializer
from ttd_data_python.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from typing import List
from typing_extensions import Annotated, NotRequired, TypedDict


class AdvertiserDataItemTypedDict(TypedDict):
    data: List[AdvertiserDataTypedDict]
    tdid: NotRequired[Nullable[str]]
    daid: NotRequired[Nullable[str]]
    ui_d2: NotRequired[Nullable[str]]
    ui_d2_token: NotRequired[Nullable[str]]
    ramp_id: NotRequired[Nullable[str]]
    core_id: NotRequired[Nullable[str]]
    euid: NotRequired[Nullable[str]]
    euid_token: NotRequired[Nullable[str]]
    i_d5: NotRequired[Nullable[str]]
    net_id: NotRequired[Nullable[str]]
    first_id: NotRequired[Nullable[str]]
    merkury_id: NotRequired[Nullable[str]]
    iqvia_ppid: NotRequired[Nullable[str]]
    cookie_mapping_partner_id: NotRequired[Nullable[str]]


class AdvertiserDataItem(BaseModel):
    data: List[AdvertiserData]

    tdid: OptionalNullable[str] = UNSET

    daid: OptionalNullable[str] = UNSET

    ui_d2: Annotated[OptionalNullable[str], pydantic.Field(alias="uiD2")] = UNSET

    ui_d2_token: Annotated[OptionalNullable[str], pydantic.Field(alias="uiD2Token")] = (
        UNSET
    )

    ramp_id: Annotated[OptionalNullable[str], pydantic.Field(alias="rampID")] = UNSET

    core_id: Annotated[OptionalNullable[str], pydantic.Field(alias="coreID")] = UNSET

    euid: OptionalNullable[str] = UNSET

    euid_token: Annotated[OptionalNullable[str], pydantic.Field(alias="euidToken")] = (
        UNSET
    )

    i_d5: Annotated[OptionalNullable[str], pydantic.Field(alias="iD5")] = UNSET

    net_id: Annotated[OptionalNullable[str], pydantic.Field(alias="netID")] = UNSET

    first_id: Annotated[OptionalNullable[str], pydantic.Field(alias="firstID")] = UNSET

    merkury_id: Annotated[OptionalNullable[str], pydantic.Field(alias="merkuryID")] = (
        UNSET
    )

    iqvia_ppid: Annotated[OptionalNullable[str], pydantic.Field(alias="iqviaPPID")] = (
        UNSET
    )

    cookie_mapping_partner_id: Annotated[
        OptionalNullable[str], pydantic.Field(alias="cookieMappingPartnerId")
    ] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "tdid",
                "daid",
                "uiD2",
                "uiD2Token",
                "rampID",
                "coreID",
                "euid",
                "euidToken",
                "iD5",
                "netID",
                "firstID",
                "merkuryID",
                "iqviaPPID",
                "cookieMappingPartnerId",
            ]
        )
        nullable_fields = set(
            [
                "tdid",
                "daid",
                "uiD2",
                "uiD2Token",
                "rampID",
                "coreID",
                "euid",
                "euidToken",
                "iD5",
                "netID",
                "firstID",
                "merkuryID",
                "iqviaPPID",
                "cookieMappingPartnerId",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
