"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from typing import Literal


AdvertiserDataResponseErrorCode = Literal[
    "Unknown",
    "BaseBidCPMMetadataTooLong",
    "MissingUserId",
    "UserNotMapped",
    "Deprecated_MissingCookieMappingPartnerId",
    "InvalidBidFactor",
    "DataNameTooLong",
    "InvalidTtlInMinutes",
    "InvalidBaseBidCPM",
]
